> # ATENCIÓN: 
> ## 1. Para lanzar el script el WIP debe estar consolidado o **todas las reglas deben tener versión**
> ## 2. Las reglas deben estar marcadas como **"DELIVERED"**
> Las otras reglas/confs se ignorarán
> ## 3. Se deben rellenar las UUAAs a desplegar/modificar
> Sino, se cogerán todas las UUAAs presentes en el WIP
> ## 4. Rellenar, si la hay, version_personalizada.
>Sino, se cogerá la última versión en el WIP para cada UUAA. De cara al TAG de la URL del job en la documentación  
>- Ejemplo:  
> https://bitbucket.gobaldevtools.bbva.com/bitbucket/projects/GL_B0HN_APP-ID-23103_DSG/repos/glgldh360gloqlt/browse/hammurabi/jobs/b0hn-gl-hmm-qlt-sustgroupsfdbkmmrule-03.json?at=refs%2Ftags%2Fv14.0.3  
> - En este caso, versión de subida:  
> 14.0.3

In [1]:
# !pip install --trusted-host=pypi.org --trusted-host=files.pythonhosted.org --user -U numpy 
# !pip install --trusted-host=pypi.org --trusted-host=files.pythonhosted.org --user "C:\Users\O005820\Downloads\numpy-2.2.4.tar.gz"
# !pip uninstall numpy
# !dir C:\Users\O005820\Downloads

In [1]:
import os
import shutil
import pandas as pd
import numpy as np
import json
import warnings
warnings.filterwarnings('ignore')
pd.set_option('display.max_columns', None)

IMPORTANTE: Indicamos UUAAs a modificar

In [2]:
UUAAs = [] #se cogerán todas las UUAAs del WIP

#selección de UUAAs
UUAAs = [
# 'B0HN',
# 'CGJ7',
# 'CTAR',
# 'DTAU',
# 'EJB6',
# 'FZPD',
# 'G5M3',
# 'J7IL',
# 'KATC',
# 'KCEG',
# 'KCPG',
# 'KCTD',
# 'KFCM',
# 'KMIG',
# 'KNFA',
'KPAN',
# 'KSRR',
# 'KSTB',
# 'KSZG',
# 'KUSU',
# 'KWTH',
# 'L9CT',
# 'L9SV',
# 'MSX9',
# 'NM7R',
# 'NOLS',
# 'P68X',
# 'P6R1',
# 'R4FU',
# 'RE4M',
# 'RZUA',
# 'SCAT',
# 'TDI3',
# 'TLHR',
# 'YFVH',
]

version_personalizada = "" #RELLENAR EN ACTUALIZACIONES MASIVAS: versión de subida de jobs (si no es para todos la misma, dejarlo vacío y cogerá la ultima versión del wip para cada UUAA)

if not UUAAs:
    print('UUAAs no declaradas (UUAAs = [])\n-> Se actualizarán todas las UUAAs presentes en el WIP con reglas DELIVERED,\nversión',version_personalizada)
else:
    UUAAs = [i.lower() for i in UUAAs]
    print('UUAAs declaradas\n-> Se actualizarán las siguientes UUAAs')
    print(UUAAs)

UUAAs declaradas
-> Se actualizarán las siguientes UUAAs
['kpan']

In [3]:
dict_tablas = {
    # 't_tdi3_cust_promo_adhesion_dp':'a',
    # 't_re4m_virtual_assistant_message':'b'
}

Confs

In [4]:
extralib_job_eur = {
    "jobName": "test",
    "description": "test",
    "size": "XS",
    "runtime": "hammurabi-lts",
    "streaming": False,
    "params": {
        "metaConfig": "gl:re4m:glgldh360gloqlt:RE4M_physical-interaction_MRField:14.0.7",
        "extraLibs": "s3://ada-eu-south-2-core-live-artifacts/dataproc/migration-artifacts/artifactory/gl-datio-spark-libs-maven-local/com/bbva/projectsdatio/c360hammcustom/1.3.4/c360hammcustom-1.3.4-jar-with-dependencies.jar" 
    },
    "env": {
        "XD_ENABLED":"true"
    },
    "tags": [ #https://docs.google.com/document/d/1nTowUue9ahe3-T69lvLM_vASvvfrueJz9qek2cYwwrk/edit?tab=t.0
        "sdm",
        "360",
        "cs",
        "gl",
        "qlt",
        "global",
        "master",
        "SDATOOL-49915"
    ],
    "kind": "processing",
    "concurrency": 10
}

In [5]:
other_job_eur = {
    "jobName": "test",
    "description": "test",
    "size": "XS",
    "runtime": "hammurabi-lts",
    "streaming": False,
    "params": {
        "metaConfig": "gl:re4m:glgldh360gloqlt:RE4M_physical-interaction_MRField:14.0.7",
    },
    "env": {
        "XD_ENABLED":"true"
    },
    "tags": [
        "sdm",
        "360",
        "cs",
        "gl",
        "qlt",
        "global",
        "master",
        "SDATOOL-49915"
    ],
    "kind": "processing",
    "concurrency": 10
}

In [6]:
extralib_job_ame = {
        "_id": "test",
        "description": "test",
        "size": "XS",
        "runtime": "hammurabi-lts",
        "streaming": False,
        "params": {
                "configUrl": "https://artifactory-gdt.central-01.nextgen.igrupobbva/artifactory/gl-datio-spark-libs-maven-dev-local/com/datiobd/c360-hammurabi/99.9.9-PR-351-SNAPSHOT/entregable_hammurabi/L9CT/L9CT_grp-clnt-cmpny-crbn-data_CIB_MRField.conf",
                "repoSecurity": "artifactory",
                "sparkHistoryEnabled": "false",
                "extraLibs": "https://artifactory-gdt.central-01.nextgen.igrupobbva/artifactory/gl-datio-spark-libs-maven-local/com/bbva/gdh/hammurabi-maxminfilter/1.2.0/hammurabi-maxminfilter-1.2.0-jar-with-dependencies.jar"
        },
        "env": {
                "XD_ENABLED":"true"
        },
        "tags": [
        "sdm",
        "360",
        "cs",
        "gl",
        "qlt",
        "global",
        "master",
        "SDATOOL-49915"
        ],
        "kind": "processing"
}

In [7]:
other_job_ame = {
    "_id": "test",
    "description": "test",
    "size": "XS",
    "runtime": "hammurabi-lts",
    "streaming": False,
    "params": {
        "configUrl": "https://artifactory-gdt.central-01.nextgen.igrupobbva/artifactory/gl-datio-spark-libs-maven-dev-local/com/datiobd/c360-hammurabi/12.1.0-PR-321-SNAPSHOT/entregable_hammurabi/KCDG/KCDG_graph-edges_KCDG_graph-nodes_MMRule.conf",
        "repoSecurity": "artifactory",
        "sparkHistoryEnabled": "false"
    },
    "env": {
        "XD_ENABLED":"true"
    },
    "tags": [
        "sdm",
        "360",
        "cs",
        "gl",
        "qlt",
        "global",
        "master",
        "SDATOOL-49915"
    ],
    "kind": "processing"
}

WIP confs

In [8]:
cols = ['STATUS IMPLANTATION','TABLE (en C360)','Secondary Table (4.3-5.2-6.4)','Conf (MRField, ORField, OCField,...)', 'Conf name', 'version  FINISHED','Url conf\nv13.0.4 (new)','Url Extralibs','IMPLANTATION TYPE']
wip = pd.read_csv('wip_final.csv', header=1)[cols].dropna(subset='version  FINISHED')

wip = wip[wip['STATUS IMPLANTATION']=="DELIVERED"]

wip['version_simple'] = wip['version  FINISHED'].str.replace("5.0.15","5.0.1").str.replace(".","").astype(int)
wip['unique_id'] = wip['TABLE (en C360)'].str[6:].str.replace('_','').str[:19] + wip['Conf name'].str.lower().str.split('_').str[-1].str.split('.').str[0]
wip['NombreJob'] = wip['Conf name'].str[:4].str.lower() + '-' + 'gl' + '-' + 'hmm' + '-' + 'qlt' + '-' + wip['unique_id'] + '-'
wip.sort_values(['version_simple','Url Extralibs','version_simple'], inplace=True, ascending=False)
wip.drop_duplicates(subset=['Conf name','version_simple'], inplace=True)
wip.reset_index(drop=True,inplace=True)
print(wip.columns)
print('\nNULOS:\n-----------')
print(wip.isnull().sum())
wip.columns = ['satus_implantation','table','secundary_table','conf_type','conf','version','ConfigURL','Extralibs','implantation','version_simple','unique_id','NombreJob']
wip['len_unique_id'] = wip.unique_id.str.len()
wip.tail(2)

Index(['STATUS IMPLANTATION', 'TABLE (en C360)',
       'Secondary Table (4.3-5.2-6.4)', 'Conf (MRField, ORField, OCField,...)',
       'Conf name', 'version  FINISHED', 'Url conf\nv13.0.4 (new)',
       'Url Extralibs', 'IMPLANTATION TYPE', 'version_simple', 'unique_id',
       'NombreJob'],
      dtype='object')

NULOS:
-----------
STATUS IMPLANTATION                        0
TABLE (en C360)                            0
Secondary Table (4.3-5.2-6.4)            878
Conf (MRField, ORField, OCField,...)    1253
Conf name                                  0
version  FINISHED                          0
Url conf\nv13.0.4 (new)                    0
Url Extralibs                           1230
IMPLANTATION TYPE                          0
version_simple                             0
unique_id                                  0
NombreJob                                  0
dtype: int64

,satus_implantation,table,secundary_table,conf_type,conf,version,ConfigURL,Extralibs,implantation,version_simple,unique_id,NombreJob,len_unique_id
1251,DELIVERED,t_dast_crypto_exchange_account,NaN,NaN,DAST_crypto-exchange-account_MRField.conf,13.0.3,https://artifactory.globaldevtools.bbva.com/ui...,NaN,Local,1303,cryptoexchangeaccoumrfield,dast-gl-hmm-qlt-cryptoexchangeaccoumrfield-,26
1252,DELIVERED,t_dast_crypto_exchange_account,NaN,NaN,DAST_crypto-exchange-account_MRObject.conf,13.0.3,https://artifactory.globaldevtools.bbva.com/ui...,NaN,Local,1303,cryptoexchangeaccoumrobject,dast-gl-hmm-qlt-cryptoexchangeaccoumrobject-,27

In [9]:
wip['table'].map(dict_tablas).fillna('')

0
1
2
3
4
       ..
1248
1249
1250
1251
1252
Name: table, Length: 1253, dtype: object

In [10]:
version = wip.sort_values('version_simple',ascending=False).version.unique()
print(version)

['18.4.3' '18.4.2' '18.4.1' '18.4.0' '18.3.9' '18.3.8' '18.3.7' '18.3.6'
 '18.3.5' '18.3.4' '18.3.3' '18.3.2' '18.3.1' '18.3.0' '18.2.0' '18.1.2'
 '18.1.1' '18.1.0' '17.8.0' '17.6.0' '17.5.0' '17.4.0' '17.3.0' '17.2.0'
 '17.1.0' '17.0.2' '17.0.1' '17.0.0' '16.1.7' '16.1.6' '16.1.5' '16.1.4'
 '16.1.3' '16.1.2' '16.1.1' '16.1.0' '16.0.9' '16.0.8' '16.0.7' '16.0.6'
 '16.0.5' '16.0.4' '16.0.3' '16.0.2' '16.0.1' '16.0.0' '15.1.0' '13.1.0'
 '13.0.3']

No puede ser mayor a 27

In [11]:
print(wip['len_unique_id'].max())

27

In [12]:
wip_confs = wip.sort_values(by='version_simple',ascending=False)[['implantation','conf','ConfigURL','Extralibs','NombreJob','version','version_simple']]

wip_confs['Extralibs'] = np.where(
    wip_confs['conf'].duplicated(keep=False),
    wip_confs.merge(wip_confs.dropna(subset=['conf','Extralibs']).rename(columns={'Extralibs':'Extralibs1'}).drop_duplicates('conf'),how='left', on='conf').Extralibs1,
    wip_confs['Extralibs']
    )

wip_confs = wip_confs.drop_duplicates(subset=['conf']).reset_index(drop=True)

wip_confs['NombreJobFinal'] = np.where(
    wip_confs['NombreJob'].duplicated(keep=False),
    wip_confs['NombreJob'] + '0' + wip_confs.groupby('NombreJob').cumcount().add(1).astype(str).str[-2:],
    wip_confs['NombreJob'] + '01'
    )
wip_confs = wip_confs.drop(columns=['NombreJob'])
wip_confs['UA'] = wip_confs['conf'].str[:4].str.lower()
wip_confs['len_NombreJobFinal'] = wip_confs.NombreJobFinal.str.len()

if not UUAAs:
    UUAAs = list(wip_confs.conf.str[:4].str.lower().sort_values().unique())
wip_confs.query('UA == @UUAAs', inplace=True) #nos quedamos con nuestras UUAAs

wip_confs

,implantation,conf,ConfigURL,Extralibs,version,version_simple,NombreJobFinal,UA,len_NombreJobFinal
0,Local,KPAN_opportunity_MRField.conf,https://artifactory.globaldevtools.bbva.com/ui...,NaN,18.4.3,1843,kpan-gl-hmm-qlt-opportunitymrfield-01,kpan,37
1,Local,KPAN_opportunity_MRObject.conf,https://artifactory.globaldevtools.bbva.com/ui...,NaN,18.4.3,1843,kpan-gl-hmm-qlt-opportunitymrobject-01,kpan,38
2,Local,KPAN_opportunity_KCOG_entity_MMRule.conf,https://artifactory.globaldevtools.bbva.com/ui...,NaN,18.4.3,1843,kpan-gl-hmm-qlt-opportunitymmrule-01,kpan,36
3,Local,KPAN_opportunity_NM7R_lead_MMRule.conf,https://artifactory.globaldevtools.bbva.com/ui...,NaN,18.4.3,1843,kpan-gl-hmm-qlt-opportunitymmrule-02,kpan,36
18,Local,KPAN_mobility-partner-oppy_MRField.conf,https://artifactory.globaldevtools.bbva.com/ui...,NaN,18.4.0,1840,kpan-gl-hmm-qlt-mobilitypartneroppymrfield-01,kpan,45
42,Local,KPAN_person-cred-fclty-psl-dp_KPAN_credit-fclt...,https://artifactory.globaldevtools.bbva.com/ui...,NaN,18.3.5,1835,kpan-gl-hmm-qlt-personcredfcltypsldmmrule-01,kpan,44
160,Local,KPAN_credit-fclty-proposals_MRField.conf,https://artifactory.globaldevtools.bbva.com/ui...,NaN,18.3.3,1833,kpan-gl-hmm-qlt-creditfcltyproposalmrfield-01,kpan,45
161,Local,KPAN_credit-fclty-proposals_KCOG_country_MMRul...,https://artifactory.globaldevtools.bbva.com/ui...,NaN,18.3.3,1833,kpan-gl-hmm-qlt-creditfcltyproposalmmrule-01,kpan,44
162,Local,KPAN_credit-fclty-proposals_KCOG_currency_MMRu...,https://artifactory.globaldevtools.bbva.com/ui...,NaN,18.3.3,1833,kpan-gl-hmm-qlt-creditfcltyproposalmmrule-02,kpan,44
163,Local,KPAN_credit-fclty-proposals_YH2J_gbl-product-h...,https://artifactory.globaldevtools.bbva.com/ui...,NaN,18.3.3,1833,kpan-gl-hmm-qlt-creditfcltyproposalmmrule-03,kpan,44
164,Local,KPAN_credit-fclty-proposals_YH2J_gbl-channel-h...,https://artifactory.globaldevtools.bbva.com/ui...,NaN,18.3.3,1833,kpan-gl-hmm-qlt-creditfcltyproposalmmrule-04,kpan,44
165,Local,KPAN_credit-fclty-proposals-dp_MRField.conf,https://artifactory.globaldevtools.bbva.com/ui...,NaN,18.3.3,1833,kpan-gl-hmm-qlt-creditfcltyproposalmrfield-02,kpan,45
166,Local,KPAN_credit-fclty-proposals-dp_KCOG_country_MM...,https://artifactory.globaldevtools.bbva.com/ui...,NaN,18.3.3,1833,kpan-gl-hmm-qlt-creditfcltyproposalmmrule-05,kpan,44
167,Local,KPAN_credit-fclty-proposals-dp_KCOG_currency_M...,https://artifactory.globaldevtools.bbva.com/ui...,NaN,18.3.3,1833,kpan-gl-hmm-qlt-creditfcltyproposalmmrule-06,kpan,44
168,Local,KPAN_credit-fclty-proposals-dp_YH2J_gbl-produc...,https://artifactory.globaldevtools.bbva.com/ui...,NaN,18.3.3,1833,kpan-gl-hmm-qlt-creditfcltyproposalmmrule-07,kpan,44
169,Local,KPAN_credit-fclty-proposals-dp_YH2J_gbl-channe...,https://artifactory.globaldevtools.bbva.com/ui...,NaN,18.3.3,1833,kpan-gl-hmm-qlt-creditfcltyproposalmmrule-08,kpan,44
170,Local,KPAN_opportunity_YH2J_gbl-channel-hier-master_...,https://artifactory.globaldevtools.bbva.com/ui...,NaN,18.3.3,1833,kpan-gl-hmm-qlt-opportunitymmrule-03,kpan,36
171,Local,KPAN_person-cred-fclty-psl-dp_MRField.conf,https://artifactory.globaldevtools.bbva.com/ui...,NaN,18.3.3,1833,kpan-gl-hmm-qlt-personcredfcltypsldmrfield-01,kpan,45
176,Local,KPAN_person-cred-fclty-psl-dp_KCOG_country_MMR...,https://artifactory.globaldevtools.bbva.com/ui...,NaN,18.3.3,1833,kpan-gl-hmm-qlt-personcredfcltypsldmmrule-02,kpan,44
177,Local,KPAN_person-cred-fclty-psl-dp_KCOG_currency_MM...,https://artifactory.globaldevtools.bbva.com/ui...,NaN,18.3.3,1833,kpan-gl-hmm-qlt-personcredfcltypsldmmrule-03,kpan,44
179,Local,KPAN_person-credit-fclty-psl_MRField.conf,https://artifactory.globaldevtools.bbva.com/ui...,NaN,18.3.3,1833,kpan-gl-hmm-qlt-personcreditfcltypsmrfield-01,kpan,45
180,Local,KPAN_person-credit-fclty-psl_KCOG_country_MMRu...,https://artifactory.globaldevtools.bbva.com/ui...,NaN,18.3.3,1833,kpan-gl-hmm-qlt-personcreditfcltypsmmrule-01,kpan,44
181,Local,KPAN_person-credit-fclty-psl_KCOG_currency_MMR...,https://artifactory.globaldevtools.bbva.com/ui...,NaN,18.3.3,1833,kpan-gl-hmm-qlt-personcreditfcltypsmmrule-02,kpan,44
286,Local,KPAN_d-c-form-oppy-cust-fields_MRField.conf,https://artifactory.globaldevtools.bbva.com/ui...,NaN,18.3.1,1831,kpan-gl-hmm-qlt-dcformoppycustfieldmrfield-01,kpan,45
287,Local,KPAN_d-c-form-opportunity_MRField.conf,https://artifactory.globaldevtools.bbva.com/ui...,NaN,18.3.1,1831,kpan-gl-hmm-qlt-dcformopportunitymrfield-01,kpan,43
484,Local,KPAN_mobility-partner-oppy_KPAN_opportunity_MM...,https://artifactory.globaldevtools.bbva.com/ui...,NaN,18.3.0,1830,kpan-gl-hmm-qlt-mobilitypartneroppymmrule-01,kpan,44
485,Local,KPAN_home-partner-oppy_KPAN_opportunity_MMRule...,https://artifactory.globaldevtools.bbva.com/ui...,NaN,18.3.0,1830,kpan-gl-hmm-qlt-homepartneroppymmrule-01,kpan,40
507,Local,KPAN_person-credit-fclty-psl_KBTQ_role-person_...,https://artifactory.globaldevtools.bbva.com/ui...,NaN,18.3.0,1830,kpan-gl-hmm-qlt-personcreditfcltypsmmrule-03,kpan,44
508,Local,KPAN_person-credit-fclty-psl_KPAN_credit-fclty...,https://artifactory.globaldevtools.bbva.com/ui...,NaN,18.3.0,1830,kpan-gl-hmm-qlt-personcreditfcltypsmmrule-04,kpan,44
521,Local,KPAN_person-cred-fclty-psl-dp_KBTQ_role-person...,https://artifactory.globaldevtools.bbva.com/ui...,NaN,18.3.0,1830,kpan-gl-hmm-qlt-personcredfcltypsldmmrule-04,kpan,44
563,Local,KPAN_home-partner-oppy_MRField.conf,https://artifactory.globaldevtools.bbva.com/ui...,NaN,17.0.2,1702,kpan-gl-hmm-qlt-homepartneroppymrfield-01,kpan,41
574,Local,KPAN_mobility-partner-oppy_P68X_vehicle-versio...,https://artifactory.globaldevtools.bbva.com/ui...,NaN,16.1.5,1615,kpan-gl-hmm-qlt-mobilitypartneroppymmrule-02,kpan,44
576,Local,KPAN_mobility-partner-oppy_KSAN_contract-globa...,https://artifactory.globaldevtools.bbva.com/ui...,NaN,16.1.4,1614,kpan-gl-hmm-qlt-mobilitypartneroppymmrule-03,kpan,44
588,Local,KPAN_oppy-status-trcblty_MRField.conf,https://artifactory.globaldevtools.bbva.com/ui...,NaN,16.1.2,1612,kpan-gl-hmm-qlt-oppystatustrcbltymrfield-01,kpan,43
606,Local,KPAN_oppy-mgr-comnt_MRField.conf,https://artifactory.globaldevtools.bbva.com/ui...,NaN,16.0.5,1605,kpan-gl-hmm-qlt-oppymgrcomntmrfield-01,kpan,38
628,Local,KPAN_mgr-comm-opportunity_KPAN_opportunity_MMR...,https://artifactory.globaldevtools.bbva.com/ui...,NaN,15.1.0,1510,kpan-gl-hmm-qlt-mgrcommopportunitymmrule-01,kpan,43
634,Local,KPAN_oppy-manager-asgn_MRField.conf,https://artifactory.globaldevtools.bbva.com/ui...,NaN,15.1.0,1510,kpan-gl-hmm-qlt-oppymanagerasgnmrfield-01,kpan,41
777,Local,KPAN_person-credit-fclty-psl_MRObject.conf,https://artifactory.globaldevtools.bbva.com/ui...,NaN,15.1.0,1510,kpan-gl-hmm-qlt-personcreditfcltypsmrobject-01,kpan,46
779,Local,KPAN_credit-fclty-proposals_MRObject.conf,https://artifactory.globaldevtools.bbva.com/ui...,NaN,15.1.0,1510,kpan-gl-hmm-qlt-creditfcltyproposalmrobject-01,kpan,46
826,Local,KPAN_mgr-comm-opportunity_MRObject.conf,https://artifactory.globaldevtools.bbva.com/ui...,NaN,15.1.0,1510,kpan-gl-hmm-qlt-mgrcommopportunitymrobject-01,kpan,45
829,Local,KPAN_mgr-comm-opportunity_MRField.conf,https://artifactory.globaldevtools.bbva.com/ui...,NaN,15.1.0,1510,kpan-gl-hmm-qlt-mgrcommopportunitymrfield-01,kpan,44

In [13]:
print(set(wip_confs.UA.unique()))
print('\n¿Mismas UUAAs? en wip_confs:')

print(set(wip_confs.UA.unique()) == set(UUAAs))

{'kpan'}

¿Mismas UUAAs? en wip_confs:
True

No puede ser mayor a 41+5 separadores: 46

In [14]:
print(wip_confs['len_NombreJobFinal'].max())

46

Revisamos ramas de cada directorio y creamos directorios

In [15]:
#Revisamos rama de cada directorio
ruta_confs = "C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/{}/glgldh360gloqlt/"
ramas = []
print(UUAAs)
for UA in UUAAs:
    print('- ',UA)
    ruta_ua = ruta_confs.format(UA)
    git = 'git -C {0} rev-parse --abbrev-ref HEAD'.format(ruta_ua)
    rama = str(os.popen(git).read()).strip()
    ramas.append(rama)
    print(rama)
    # if not os.path.exists(ruta_ua+'/hammurabi/jobs/'):
    #     os.makedirs(ruta_ua+'/hammurabi/jobs/')

['kpan']
-  kpan
feature/MVP_4Q25_c360_06_02_2025

In [16]:
print('ramas unicas (siempre debemos actuar sobre una)')
print(list(np.unique(ramas)))

ramas unicas (siempre debemos actuar sobre una)
[np.str_('feature/MVP_4Q25_c360_06_02_2025')]

In [17]:
#Reseteamos directorios (eliminamos y volvemos a crear)
ruta_confs = "C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/{}/glgldh360gloqlt/"
geo_ruta_dict = {
    'europa': '01',
    'america':'02',
    'america-ada':'02'
    }
print(UUAAs)
for UA in UUAAs:
    print(UA)
    ruta_ua = ruta_confs.format(UA)
    shutil.rmtree(ruta_ua+'/hammurabi/jobs/')
    for geo_ruta in geo_ruta_dict.keys():
        os.makedirs(ruta_ua+'/hammurabi/jobs/'+geo_ruta)

['kpan']
kpan

Creamos jobs en cada directorio

In [18]:
version_desplegada_UA = wip_confs.sort_values('version_simple',ascending=False).drop_duplicates('UA')[['UA','version']].rename(columns={'version':'version_despliegue'})
wip_confs = wip_confs.merge(version_desplegada_UA,how='left',on='UA')
version_desplegada_UA

     UA version_despliegue
0  kpan             18.4.3

In [19]:
print("mismas uuaas? \nversion_desplegada_UA")

set(version_desplegada_UA.UA) == set(UUAAs)

mismas uuaas?
version_desplegada_UA

True

In [20]:
print('UUAAs afectadas:')
print(sorted(set(wip_confs.UA.unique())))
print("\nmismas uuaas? \nwip_confs")

set(wip_confs.UA.unique()) == set(UUAAs)

UUAAs afectadas:
['kpan']

mismas uuaas?
wip_confs

True

In [21]:
extralib_confs = wip_confs.dropna(subset='Extralibs')
other_confs = wip_confs[wip_confs.Extralibs.isnull()]

In [22]:
#SI HEMOS CREADO UN NUEVO REPO INCLUIR EN './repos/repos.csv' desde https://docs.google.com/spreadsheets/d/1aLELrHoXPwm8CSY2a6DN6DRqoIkruHQO37JrQcaZFNM/edit?gid=1588638166#gid=1588638166
uuaas_repos = pd.read_csv('./repos/repos.csv')
uuaas_repos.UUAA = uuaas_repos.UUAA.str.lower()
uuaas_repos.index = uuaas_repos.UUAA
dict_project_ua = uuaas_repos.project.to_dict()

In [23]:
for ua in UUAAs:
    print(ua,'- ¿Está en el inventario de repos? ("repos\\repos.csv"):\n', ua in list(uuaas_repos.UUAA))
    if not ua in list(uuaas_repos.UUAA):
        print("\t¡ATENCIÓN! Añadir UA {0} a 'repos\\repos.csv'".format(ua))

kpan - ¿Está en el inventario de repos? ("repos\repos.csv"):
 True

In [24]:
geo_ruta_dict

{'europa': '01', 'america': '02', 'america-ada': '02'}

In [25]:
geos = ["gl"]#,"es","co","pe","ar","mx"]
conf_job_dict = {}
#Extralibs
for index, row in extralib_confs.iterrows():
    for geo in geos:
        for geo_ruta in geo_ruta_dict.keys():
            if row["implantation"]=="Holding":
                geo = "gl"
            nombre_job = row['NombreJobFinal']
            nombre_job = nombre_job[0:5] + geo + nombre_job[7:]
            ruta_ua = ruta_confs.format(row['UA'])
            if geo_ruta == 'europa': #para europa, nuevo formato ADA
                extralib_job_eur['description'] = nombre_job
                extralib_job_eur['jobName'] = nombre_job
                extralib_job_eur['params']['metaConfig'] = "gl:" + row['UA'] + ":" + "glgldh360gloqlt" + ":" + row['conf'].replace('.conf','') + ":" + row['version']
                extralib_job_eur['params']['extraLibs'] = row['Extralibs'].replace('https://artifactory.globaldevtools.bbva.com/ui/repos/tree/General/','s3://ada-eu-south-2-core-live-artifacts/dataproc/migration-artifacts/artifactory/'.format(geo_ruta_dict[geo_ruta]))
                extralib_job_eur['params']['extraLibs'] = row['Extralibs'].replace('https://artifactory-gdt.central-01.nextgen.igrupobbva/artifactory/','s3://ada-eu-south-2-core-live-artifacts/dataproc/migration-artifacts/artifactory/'.format(geo_ruta_dict[geo_ruta]))
                extralib_job = extralib_job_eur
            elif geo_ruta == 'america-ada': #para america-ada, nuevo formato ADA
                nombre_job_ada = row['NombreJobFinal']
                extralib_job_eur['description'] = nombre_job
                extralib_job_eur['jobName'] = nombre_job
                extralib_job_eur['params']['metaConfig'] = "gl:" + row['UA'] + ":" + "glgldh360gloqlt" + ":" + row['conf'].replace('.conf','') + ":" + row['version']
                extralib_job_eur['params']['extraLibs'] = row['Extralibs'].replace('https://artifactory.globaldevtools.bbva.com/ui/repos/tree/General/','s3://ada-us-east-1-core-live-artifacts/dataproc/migration-artifacts/artifactory/'.format(geo_ruta_dict[geo_ruta]))
                extralib_job_eur['params']['extraLibs'] = row['Extralibs'].replace('https://artifactory-gdt.central-01.nextgen.igrupobbva/artifactory/','s3://ada-us-east-1-core-live-artifacts/dataproc/migration-artifacts/artifactory/'.format(geo_ruta_dict[geo_ruta]))
                extralib_job = extralib_job_eur
            elif geo_ruta == 'america': #para america, por ahora seguimos igual
                extralib_job_ame['description'] = nombre_job
                extralib_job_ame['_id'] = nombre_job
                extralib_job_ame['params']['configUrl'] = row['ConfigURL'].replace('https://artifactory.globaldevtools.bbva.com/ui/repos/tree/General/','https://artifactory-gdt.central-{0}.nextgen.igrupobbva/artifactory/'.format(geo_ruta_dict[geo_ruta]))
                extralib_job_ame['params']['extraLibs'] = row['Extralibs'].replace('https://artifactory.globaldevtools.bbva.com/ui/repos/tree/General/','https://artifactory-gdt.central-{0}.nextgen.igrupobbva/artifactory/'.format(geo_ruta_dict[geo_ruta]))
                extralib_job_ame['params']['extraLibs'] = row['Extralibs'].replace('https://artifactory-gdt.central-01.nextgen.igrupobbva/artifactory/','https://artifactory-gdt.central-{0}.nextgen.igrupobbva/artifactory/'.format(geo_ruta_dict[geo_ruta]))
                extralib_job = extralib_job_ame
            with open(ruta_ua + '/hammurabi/jobs/' + geo_ruta + '/' + nombre_job + '.json', 'w', encoding='utf-8') as f:
                json.dump(extralib_job, f, ensure_ascii=False, indent=4)
            print(ruta_ua + '/hammurabi/jobs/' + geo_ruta + '/' + nombre_job + '.json')

        if not version_personalizada:
            conf_job_dict[row['conf']] = (
                "https://bitbucket.globaldevtools.bbva.com/bitbucket/projects/" + dict_project_ua[row['UA']] + "/repos/glgldh360gloqlt/browse/hammurabi/jobs/"+list(geo_ruta_dict.keys())[0]+'/'+nombre_job+".json"+"?at=refs%2Ftags%2Fv"+row['version_despliegue'] + "\n"
                "https://bitbucket.globaldevtools.bbva.com/bitbucket/projects/" + dict_project_ua[row['UA']] + "/repos/glgldh360gloqlt/browse/hammurabi/jobs/"+list(geo_ruta_dict.keys())[1]+'/'+nombre_job+".json"+"?at=refs%2Ftags%2Fv"+row['version_despliegue']
                )
        else:
            conf_job_dict[row['conf']] = (
                "https://bitbucket.globaldevtools.bbva.com/bitbucket/projects/" + dict_project_ua[row['UA']] + "/repos/glgldh360gloqlt/browse/hammurabi/jobs/"+list(geo_ruta_dict.keys())[0]+'/'+nombre_job+".json"+"?at=refs%2Ftags%2Fv"+version_personalizada + "\n"
                "https://bitbucket.globaldevtools.bbva.com/bitbucket/projects/" + dict_project_ua[row['UA']] + "/repos/glgldh360gloqlt/browse/hammurabi/jobs/"+list(geo_ruta_dict.keys())[1]+'/'+nombre_job+".json"+"?at=refs%2Ftags%2Fv"+version_personalizada   
                )

#Others
for index, row in other_confs.iterrows():
    for geo in geos:
        for geo_ruta in geo_ruta_dict.keys():
            if row["implantation"]=="Holding":
                geo = "gl"
            nombre_job = row['NombreJobFinal']
            nombre_job = nombre_job[0:5] + geo + nombre_job[7:]
            ruta_ua = ruta_confs.format(row['UA'])
            if geo_ruta == 'europa':        #para europa, nuevo formato ADA
                other_job_eur['description'] = nombre_job
                other_job_eur['jobName'] = nombre_job
                other_job_eur['params']['metaConfig'] = "gl:" + row['UA'] + ":" + "glgldh360gloqlt" + ":" + row['conf'].replace('.conf','') + ":" + row['version']
                other_job = other_job_eur
            elif geo_ruta == 'america-ada': #para europa, nuevo formato ADA
                nombre_job = row['NombreJobFinal']
                other_job_eur['description'] = nombre_job
                other_job_eur['jobName'] = nombre_job
                other_job_eur['params']['metaConfig'] = "gl:" + row['UA'] + ":" + "glgldh360gloqlt" + ":" + row['conf'].replace('.conf','') + ":" + row['version']
                other_job = other_job_eur
            elif geo_ruta == 'america':     #para america, por ahora seguimos igual
                other_job_ame['description'] = nombre_job
                other_job_ame['_id'] = nombre_job
                other_job_ame['params']['configUrl'] = row['ConfigURL'].replace('https://artifactory.globaldevtools.bbva.com/ui/repos/tree/General/','https://artifactory-gdt.central-{0}.nextgen.igrupobbva/artifactory/'.format(geo_ruta_dict[geo_ruta]))
                other_job = other_job_ame
            with open(ruta_ua + '/hammurabi/jobs/' + geo_ruta + '/' + nombre_job + '.json', 'w', encoding='utf-8') as f:
                json.dump(other_job, f, ensure_ascii=False, indent=4)
            print(ruta_ua + '/hammurabi/jobs/' + geo_ruta + '/' + nombre_job + '.json')

        if not version_personalizada:
            conf_job_dict[row['conf']] = (
                "https://bitbucket.globaldevtools.bbva.com/bitbucket/projects/" + dict_project_ua[row['UA']] + "/repos/glgldh360gloqlt/browse/hammurabi/jobs/"+list(geo_ruta_dict.keys())[0]+'/'+nombre_job+".json"+"?at=refs%2Ftags%2Fv"+row['version_despliegue'] + "\n"
                "https://bitbucket.globaldevtools.bbva.com/bitbucket/projects/" + dict_project_ua[row['UA']] + "/repos/glgldh360gloqlt/browse/hammurabi/jobs/"+list(geo_ruta_dict.keys())[1]+'/'+nombre_job+".json"+"?at=refs%2Ftags%2Fv"+row['version_despliegue']
                )
        else:
            conf_job_dict[row['conf']] = (
                "https://bitbucket.globaldevtools.bbva.com/bitbucket/projects/" + dict_project_ua[row['UA']] + "/repos/glgldh360gloqlt/browse/hammurabi/jobs/"+list(geo_ruta_dict.keys())[0]+'/'+nombre_job+".json"+"?at=refs%2Ftags%2Fv"+version_personalizada + "\n"
                "https://bitbucket.globaldevtools.bbva.com/bitbucket/projects/" + dict_project_ua[row['UA']] + "/repos/glgldh360gloqlt/browse/hammurabi/jobs/"+list(geo_ruta_dict.keys())[1]+'/'+nombre_job+".json"+"?at=refs%2Ftags%2Fv"+version_personalizada   
                )

C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/europa/kpan-gl-hmm-qlt-opportunitymrfield-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america/kpan-gl-hmm-qlt-opportunitymrfield-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america-ada/kpan-gl-hmm-qlt-opportunitymrfield-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/europa/kpan-gl-hmm-qlt-opportunitymrobject-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america/kpan-gl-hmm-qlt-opportunitymrobject-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america-ada/kpan-gl-hmm-qlt-opportunitymrobject-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/europa/kpan-gl-hmm-qlt-opportunitymmrule-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america/kpan-gl-hmm-qlt-opportunitymmrule-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america-ada/kpan-gl-hmm-qlt-opportunitymmrule-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/europa/kpan-gl-hmm-qlt-opportunitymmrule-02.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america/kpan-gl-hmm-qlt-opportunitymmrule-02.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america-ada/kpan-gl-hmm-qlt-opportunitymmrule-02.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/europa/kpan-gl-hmm-qlt-mobilitypartneroppymrfield-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america/kpan-gl-hmm-qlt-mobilitypartneroppymrfield-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america-ada/kpan-gl-hmm-qlt-mobilitypartneroppymrfield-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/europa/kpan-gl-hmm-qlt-personcredfcltypsldmmrule-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america/kpan-gl-hmm-qlt-personcredfcltypsldmmrule-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america-ada/kpan-gl-hmm-qlt-personcredfcltypsldmmrule-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/europa/kpan-gl-hmm-qlt-creditfcltyproposalmrfield-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america/kpan-gl-hmm-qlt-creditfcltyproposalmrfield-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america-ada/kpan-gl-hmm-qlt-creditfcltyproposalmrfield-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/europa/kpan-gl-hmm-qlt-creditfcltyproposalmmrule-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america/kpan-gl-hmm-qlt-creditfcltyproposalmmrule-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america-ada/kpan-gl-hmm-qlt-creditfcltyproposalmmrule-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/europa/kpan-gl-hmm-qlt-creditfcltyproposalmmrule-02.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america/kpan-gl-hmm-qlt-creditfcltyproposalmmrule-02.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america-ada/kpan-gl-hmm-qlt-creditfcltyproposalmmrule-02.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/europa/kpan-gl-hmm-qlt-creditfcltyproposalmmrule-03.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america/kpan-gl-hmm-qlt-creditfcltyproposalmmrule-03.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america-ada/kpan-gl-hmm-qlt-creditfcltyproposalmmrule-03.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/europa/kpan-gl-hmm-qlt-creditfcltyproposalmmrule-04.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america/kpan-gl-hmm-qlt-creditfcltyproposalmmrule-04.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america-ada/kpan-gl-hmm-qlt-creditfcltyproposalmmrule-04.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/europa/kpan-gl-hmm-qlt-creditfcltyproposalmrfield-02.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america/kpan-gl-hmm-qlt-creditfcltyproposalmrfield-02.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america-ada/kpan-gl-hmm-qlt-creditfcltyproposalmrfield-02.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/europa/kpan-gl-hmm-qlt-creditfcltyproposalmmrule-05.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america/kpan-gl-hmm-qlt-creditfcltyproposalmmrule-05.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america-ada/kpan-gl-hmm-qlt-creditfcltyproposalmmrule-05.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/europa/kpan-gl-hmm-qlt-creditfcltyproposalmmrule-06.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america/kpan-gl-hmm-qlt-creditfcltyproposalmmrule-06.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america-ada/kpan-gl-hmm-qlt-creditfcltyproposalmmrule-06.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/europa/kpan-gl-hmm-qlt-creditfcltyproposalmmrule-07.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america/kpan-gl-hmm-qlt-creditfcltyproposalmmrule-07.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america-ada/kpan-gl-hmm-qlt-creditfcltyproposalmmrule-07.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/europa/kpan-gl-hmm-qlt-creditfcltyproposalmmrule-08.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america/kpan-gl-hmm-qlt-creditfcltyproposalmmrule-08.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america-ada/kpan-gl-hmm-qlt-creditfcltyproposalmmrule-08.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/europa/kpan-gl-hmm-qlt-opportunitymmrule-03.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america/kpan-gl-hmm-qlt-opportunitymmrule-03.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america-ada/kpan-gl-hmm-qlt-opportunitymmrule-03.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/europa/kpan-gl-hmm-qlt-personcredfcltypsldmrfield-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america/kpan-gl-hmm-qlt-personcredfcltypsldmrfield-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america-ada/kpan-gl-hmm-qlt-personcredfcltypsldmrfield-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/europa/kpan-gl-hmm-qlt-personcredfcltypsldmmrule-02.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america/kpan-gl-hmm-qlt-personcredfcltypsldmmrule-02.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america-ada/kpan-gl-hmm-qlt-personcredfcltypsldmmrule-02.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/europa/kpan-gl-hmm-qlt-personcredfcltypsldmmrule-03.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america/kpan-gl-hmm-qlt-personcredfcltypsldmmrule-03.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america-ada/kpan-gl-hmm-qlt-personcredfcltypsldmmrule-03.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/europa/kpan-gl-hmm-qlt-personcreditfcltypsmrfield-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america/kpan-gl-hmm-qlt-personcreditfcltypsmrfield-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america-ada/kpan-gl-hmm-qlt-personcreditfcltypsmrfield-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/europa/kpan-gl-hmm-qlt-personcreditfcltypsmmrule-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america/kpan-gl-hmm-qlt-personcreditfcltypsmmrule-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america-ada/kpan-gl-hmm-qlt-personcreditfcltypsmmrule-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/europa/kpan-gl-hmm-qlt-personcreditfcltypsmmrule-02.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america/kpan-gl-hmm-qlt-personcreditfcltypsmmrule-02.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america-ada/kpan-gl-hmm-qlt-personcreditfcltypsmmrule-02.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/europa/kpan-gl-hmm-qlt-dcformoppycustfieldmrfield-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america/kpan-gl-hmm-qlt-dcformoppycustfieldmrfield-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america-ada/kpan-gl-hmm-qlt-dcformoppycustfieldmrfield-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/europa/kpan-gl-hmm-qlt-dcformopportunitymrfield-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america/kpan-gl-hmm-qlt-dcformopportunitymrfield-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america-ada/kpan-gl-hmm-qlt-dcformopportunitymrfield-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/europa/kpan-gl-hmm-qlt-mobilitypartneroppymmrule-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america/kpan-gl-hmm-qlt-mobilitypartneroppymmrule-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america-ada/kpan-gl-hmm-qlt-mobilitypartneroppymmrule-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/europa/kpan-gl-hmm-qlt-homepartneroppymmrule-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america/kpan-gl-hmm-qlt-homepartneroppymmrule-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america-ada/kpan-gl-hmm-qlt-homepartneroppymmrule-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/europa/kpan-gl-hmm-qlt-personcreditfcltypsmmrule-03.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america/kpan-gl-hmm-qlt-personcreditfcltypsmmrule-03.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america-ada/kpan-gl-hmm-qlt-personcreditfcltypsmmrule-03.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/europa/kpan-gl-hmm-qlt-personcreditfcltypsmmrule-04.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america/kpan-gl-hmm-qlt-personcreditfcltypsmmrule-04.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america-ada/kpan-gl-hmm-qlt-personcreditfcltypsmmrule-04.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/europa/kpan-gl-hmm-qlt-personcredfcltypsldmmrule-04.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america/kpan-gl-hmm-qlt-personcredfcltypsldmmrule-04.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america-ada/kpan-gl-hmm-qlt-personcredfcltypsldmmrule-04.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/europa/kpan-gl-hmm-qlt-homepartneroppymrfield-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america/kpan-gl-hmm-qlt-homepartneroppymrfield-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america-ada/kpan-gl-hmm-qlt-homepartneroppymrfield-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/europa/kpan-gl-hmm-qlt-mobilitypartneroppymmrule-02.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america/kpan-gl-hmm-qlt-mobilitypartneroppymmrule-02.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america-ada/kpan-gl-hmm-qlt-mobilitypartneroppymmrule-02.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/europa/kpan-gl-hmm-qlt-mobilitypartneroppymmrule-03.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america/kpan-gl-hmm-qlt-mobilitypartneroppymmrule-03.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america-ada/kpan-gl-hmm-qlt-mobilitypartneroppymmrule-03.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/europa/kpan-gl-hmm-qlt-oppystatustrcbltymrfield-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america/kpan-gl-hmm-qlt-oppystatustrcbltymrfield-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america-ada/kpan-gl-hmm-qlt-oppystatustrcbltymrfield-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/europa/kpan-gl-hmm-qlt-oppymgrcomntmrfield-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america/kpan-gl-hmm-qlt-oppymgrcomntmrfield-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america-ada/kpan-gl-hmm-qlt-oppymgrcomntmrfield-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/europa/kpan-gl-hmm-qlt-mgrcommopportunitymmrule-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america/kpan-gl-hmm-qlt-mgrcommopportunitymmrule-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america-ada/kpan-gl-hmm-qlt-mgrcommopportunitymmrule-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/europa/kpan-gl-hmm-qlt-oppymanagerasgnmrfield-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america/kpan-gl-hmm-qlt-oppymanagerasgnmrfield-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america-ada/kpan-gl-hmm-qlt-oppymanagerasgnmrfield-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/europa/kpan-gl-hmm-qlt-personcreditfcltypsmrobject-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america/kpan-gl-hmm-qlt-personcreditfcltypsmrobject-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america-ada/kpan-gl-hmm-qlt-personcreditfcltypsmrobject-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/europa/kpan-gl-hmm-qlt-creditfcltyproposalmrobject-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america/kpan-gl-hmm-qlt-creditfcltyproposalmrobject-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america-ada/kpan-gl-hmm-qlt-creditfcltyproposalmrobject-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/europa/kpan-gl-hmm-qlt-mgrcommopportunitymrobject-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america/kpan-gl-hmm-qlt-mgrcommopportunitymrobject-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america-ada/kpan-gl-hmm-qlt-mgrcommopportunitymrobject-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/europa/kpan-gl-hmm-qlt-mgrcommopportunitymrfield-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america/kpan-gl-hmm-qlt-mgrcommopportunitymrfield-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs/kpan/glgldh360gloqlt//hammurabi/jobs/america-ada/kpan-gl-hmm-qlt-mgrcommopportunitymrfield-01.json

In [26]:
conf_url_OLD = pd.read_csv('wip_conf_url_OLD.csv',sep=',')
conf_url_OLD['UA'] = conf_url_OLD.conf.str[:4].str.lower()
conf_url_OLD.query('UA != @UUAAs',inplace=True)
print("UUAAs NO afectadas:\n",list(conf_url_OLD.UA.sort_values().unique()))
print("UUAAs SI afectadas:\n",UUAAs)
#personalizar eliminación
# conf_url_OLD.query('UA != "ksci"',inplace=True)
conf_url_OLD.drop(columns='UA',inplace=True)

conf_url_OLD

UUAAs NO afectadas:
 ['b0hn', 'cgj7', 'cmov', 'ctar', 'dast', 'dtau', 'ejb6', 'fzpd', 'g5m3', 'j7il', 'katc', 'kcdg', 'kceg', 'kcpg', 'kctd', 'kfcm', 'kmig', 'knfa', 'ksrr', 'kstb', 'kszg', 'kusu', 'kwth', 'l9ct', 'l9sv', 'msx9', 'nm7r', 'nols', 'p68x', 'p6r1', 'r4fu', 're4m', 'rzua', 'scat', 'tdi3', 'tlhr', 'yfvh']
UUAAs SI afectadas:
 ['kpan']

,conf,job_url,table,secundary_table,job,version
0,B0HN_agg-output-ems-hgl_MRField.conf,https://bitbucket.globaldevtools.bbva.com/bitb...,t_b0hn_agg_output_ems_hgl,NaN,b0hn-gl-hmm-qlt-aggoutputemshglmrfield-01.json,"""18.3.3"""
1,B0HN_agg-output-ems-hgl_MRObject.conf,https://bitbucket.globaldevtools.bbva.com/bitb...,t_b0hn_agg_output_ems_hgl,NaN,b0hn-gl-hmm-qlt-aggoutputemshglmrobject-01.json,"""18.3.3"""
2,B0HN_agg-output-ems-hgl_KSAG_holding-business-...,https://bitbucket.globaldevtools.bbva.com/bitb...,t_b0hn_agg_output_ems_hgl,t_ksag_holding_business_group,b0hn-gl-hmm-qlt-aggoutputemshglmmrule-01.json,"""18.3.3"""
3,B0HN_sust-group-mark_MRField.conf,https://bitbucket.globaldevtools.bbva.com/bitb...,t_b0hn_sust_group_mark,NaN,b0hn-gl-hmm-qlt-sustgroupmarkmrfield-01.json,"""18.3.3"""
4,B0HN_sust-group-mark_MRObject.conf,https://bitbucket.globaldevtools.bbva.com/bitb...,t_b0hn_sust_group_mark,NaN,b0hn-gl-hmm-qlt-sustgroupmarkmrobject-01.json,"""18.3.3"""
...,...,...,...,...,...,...
885,TDI3_tracking-code_L9SV_placement-display_MMRu...,https://bitbucket.globaldevtools.bbva.com/bitb...,t_tdi3_tracking_code,t_l9sv_placement_display,tdi3-gl-hmm-qlt-trackingcodemmrule-01.json,"""18.3.3"""
886,TDI3_tracking-code_TDI3_communication_MMRule.conf,https://bitbucket.globaldevtools.bbva.com/bitb...,t_tdi3_tracking_code,t_tdi3_communication,tdi3-gl-hmm-qlt-trackingcodemmrule-02.json,"""18.3.3"""
887,TLHR_complaints-claims_MRField.conf,https://bitbucket.globaldevtools.bbva.com/bitb...,t_tlhr_complaints_claims,NaN,tlhr-gl-hmm-qlt-complaintsclaimsmrfield-01.json,"""18.3.3"""
888,TLHR_complaints-claims_MRObject.conf,https://bitbucket.globaldevtools.bbva.com/bitb...,t_tlhr_complaints_claims,NaN,tlhr-gl-hmm-qlt-complaintsclaimsmrobject-01.json,"""18.3.3"""
889,YFVH_cards-calc-balances_MRField.conf,https://bitbucket.globaldevtools.bbva.com/bitb...,t_yfvh_cards_calc_balances,NaN,yfvh-gl-hmm-qlt-cardscalcbalancesmrfield-01.json,"""18.3.6"""

In [27]:
conf_url_NEW = pd.DataFrame(conf_job_dict.items(), columns=['conf', 'job_url']).merge(wip[['table','secundary_table','conf']].drop_duplicates(subset='conf').dropna(subset=['table','conf']),how='left',on='conf')
conf_url_NEW['job'] = conf_url_NEW.job_url.apply(lambda x: x.split('/')[-1])
conf_url_NEW['job'] = conf_url_NEW.job.apply(lambda x: x.split('?')[0])
conf_url_NEW['version'] = conf_url_NEW.job_url.str[-6:]
conf_url = pd.concat([conf_url_OLD,conf_url_NEW],axis=0)
conf_url['version'] = '"' + conf_url['version'].str.replace('"','') + '"'
conf_url['type'] = conf_url.conf.str.extract(r'_(.{6,8}).conf').replace({'MRField':1, 'MRObject':2, 'MMRule':3})
conf_url.sort_values(['table','type'], inplace=True)
conf_url.drop(columns='type', inplace=True)
conf_url.to_csv('wip_conf_url_NEW.csv',sep=';',index=False)
conf_url

,conf,job_url,table,secundary_table,job,version
0,B0HN_agg-output-ems-hgl_MRField.conf,https://bitbucket.globaldevtools.bbva.com/bitb...,t_b0hn_agg_output_ems_hgl,NaN,b0hn-gl-hmm-qlt-aggoutputemshglmrfield-01.json,"""18.3.3"""
1,B0HN_agg-output-ems-hgl_MRObject.conf,https://bitbucket.globaldevtools.bbva.com/bitb...,t_b0hn_agg_output_ems_hgl,NaN,b0hn-gl-hmm-qlt-aggoutputemshglmrobject-01.json,"""18.3.3"""
2,B0HN_agg-output-ems-hgl_KSAG_holding-business-...,https://bitbucket.globaldevtools.bbva.com/bitb...,t_b0hn_agg_output_ems_hgl,t_ksag_holding_business_group,b0hn-gl-hmm-qlt-aggoutputemshglmmrule-01.json,"""18.3.3"""
3,B0HN_sust-group-mark_MRField.conf,https://bitbucket.globaldevtools.bbva.com/bitb...,t_b0hn_sust_group_mark,NaN,b0hn-gl-hmm-qlt-sustgroupmarkmrfield-01.json,"""18.3.3"""
4,B0HN_sust-group-mark_MRObject.conf,https://bitbucket.globaldevtools.bbva.com/bitb...,t_b0hn_sust_group_mark,NaN,b0hn-gl-hmm-qlt-sustgroupmarkmrobject-01.json,"""18.3.3"""
...,...,...,...,...,...,...
885,TDI3_tracking-code_L9SV_placement-display_MMRu...,https://bitbucket.globaldevtools.bbva.com/bitb...,t_tdi3_tracking_code,t_l9sv_placement_display,tdi3-gl-hmm-qlt-trackingcodemmrule-01.json,"""18.3.3"""
886,TDI3_tracking-code_TDI3_communication_MMRule.conf,https://bitbucket.globaldevtools.bbva.com/bitb...,t_tdi3_tracking_code,t_tdi3_communication,tdi3-gl-hmm-qlt-trackingcodemmrule-02.json,"""18.3.3"""
887,TLHR_complaints-claims_MRField.conf,https://bitbucket.globaldevtools.bbva.com/bitb...,t_tlhr_complaints_claims,NaN,tlhr-gl-hmm-qlt-complaintsclaimsmrfield-01.json,"""18.3.3"""
888,TLHR_complaints-claims_MRObject.conf,https://bitbucket.globaldevtools.bbva.com/bitb...,t_tlhr_complaints_claims,NaN,tlhr-gl-hmm-qlt-complaintsclaimsmrobject-01.json,"""18.3.3"""
889,YFVH_cards-calc-balances_MRField.conf,https://bitbucket.globaldevtools.bbva.com/bitb...,t_yfvh_cards_calc_balances,NaN,yfvh-gl-hmm-qlt-cardscalcbalancesmrfield-01.json,"""18.3.6"""

In [28]:
version = '"18.4.3"'
print('uuaas:',conf_url[conf_url.version == version].conf.str[:4].unique())
conf_url_version = conf_url[conf_url.version == version]
conf_url_version

uuaas: ['KPAN']

,conf,job_url,table,secundary_table,job,version
6,KPAN_credit-fclty-proposals_MRField.conf,https://bitbucket.globaldevtools.bbva.com/bitb...,t_kpan_credit_fclty_proposals,NaN,kpan-gl-hmm-qlt-creditfcltyproposalmrfield-01....,"""18.4.3"""
38,KPAN_credit-fclty-proposals_MRObject.conf,https://bitbucket.globaldevtools.bbva.com/bitb...,t_kpan_credit_fclty_proposals,NaN,kpan-gl-hmm-qlt-creditfcltyproposalmrobject-01...,"""18.4.3"""
7,KPAN_credit-fclty-proposals_KCOG_country_MMRul...,https://bitbucket.globaldevtools.bbva.com/bitb...,t_kpan_credit_fclty_proposals,t_kcog_country,kpan-gl-hmm-qlt-creditfcltyproposalmmrule-01.json,"""18.4.3"""
8,KPAN_credit-fclty-proposals_KCOG_currency_MMRu...,https://bitbucket.globaldevtools.bbva.com/bitb...,t_kpan_credit_fclty_proposals,t_kcog_currency,kpan-gl-hmm-qlt-creditfcltyproposalmmrule-02.json,"""18.4.3"""
9,KPAN_credit-fclty-proposals_YH2J_gbl-product-h...,https://bitbucket.globaldevtools.bbva.com/bitb...,t_kpan_credit_fclty_proposals,t_yh2j_gbl_product_hier_master,kpan-gl-hmm-qlt-creditfcltyproposalmmrule-03.json,"""18.4.3"""
10,KPAN_credit-fclty-proposals_YH2J_gbl-channel-h...,https://bitbucket.globaldevtools.bbva.com/bitb...,t_kpan_credit_fclty_proposals,t_yh2j_gbl_channel_hier_master,kpan-gl-hmm-qlt-creditfcltyproposalmmrule-04.json,"""18.4.3"""
11,KPAN_credit-fclty-proposals-dp_MRField.conf,https://bitbucket.globaldevtools.bbva.com/bitb...,t_kpan_credit_fclty_proposals_dp,NaN,kpan-gl-hmm-qlt-creditfcltyproposalmrfield-02....,"""18.4.3"""
12,KPAN_credit-fclty-proposals-dp_KCOG_country_MM...,https://bitbucket.globaldevtools.bbva.com/bitb...,t_kpan_credit_fclty_proposals_dp,t_kcog_country,kpan-gl-hmm-qlt-creditfcltyproposalmmrule-05.json,"""18.4.3"""
13,KPAN_credit-fclty-proposals-dp_KCOG_currency_M...,https://bitbucket.globaldevtools.bbva.com/bitb...,t_kpan_credit_fclty_proposals_dp,t_kcog_currency,kpan-gl-hmm-qlt-creditfcltyproposalmmrule-06.json,"""18.4.3"""
14,KPAN_credit-fclty-proposals-dp_YH2J_gbl-produc...,https://bitbucket.globaldevtools.bbva.com/bitb...,t_kpan_credit_fclty_proposals_dp,t_yh2j_gbl_product_hier_master,kpan-gl-hmm-qlt-creditfcltyproposalmmrule-07.json,"""18.4.3"""
15,KPAN_credit-fclty-proposals-dp_YH2J_gbl-channe...,https://bitbucket.globaldevtools.bbva.com/bitb...,t_kpan_credit_fclty_proposals_dp,t_yh2j_gbl_channel_hier_master,kpan-gl-hmm-qlt-creditfcltyproposalmmrule-08.json,"""18.4.3"""
24,KPAN_d-c-form-opportunity_MRField.conf,https://bitbucket.globaldevtools.bbva.com/bitb...,t_kpan_d_c_form_opportunity,NaN,kpan-gl-hmm-qlt-dcformopportunitymrfield-01.json,"""18.4.3"""
23,KPAN_d-c-form-oppy-cust-fields_MRField.conf,https://bitbucket.globaldevtools.bbva.com/bitb...,t_kpan_d_c_form_oppy_cust_fields,NaN,kpan-gl-hmm-qlt-dcformoppycustfieldmrfield-01....,"""18.4.3"""
30,KPAN_home-partner-oppy_MRField.conf,https://bitbucket.globaldevtools.bbva.com/bitb...,t_kpan_home_partner_oppy,NaN,kpan-gl-hmm-qlt-homepartneroppymrfield-01.json,"""18.4.3"""
26,KPAN_home-partner-oppy_KPAN_opportunity_MMRule...,https://bitbucket.globaldevtools.bbva.com/bitb...,t_kpan_home_partner_oppy,t_kpan_opportunity,kpan-gl-hmm-qlt-homepartneroppymmrule-01.json,"""18.4.3"""
40,KPAN_mgr-comm-opportunity_MRField.conf,https://bitbucket.globaldevtools.bbva.com/bitb...,t_kpan_mgr_comm_opportunity,NaN,kpan-gl-hmm-qlt-mgrcommopportunitymrfield-01.json,"""18.4.3"""
39,KPAN_mgr-comm-opportunity_MRObject.conf,https://bitbucket.globaldevtools.bbva.com/bitb...,t_kpan_mgr_comm_opportunity,NaN,kpan-gl-hmm-qlt-mgrcommopportunitymrobject-01....,"""18.4.3"""
35,KPAN_mgr-comm-opportunity_KPAN_opportunity_MMR...,https://bitbucket.globaldevtools.bbva.com/bitb...,t_kpan_mgr_comm_opportunity,t_kpan_opportunity,kpan-gl-hmm-qlt-mgrcommopportunitymmrule-01.json,"""18.4.3"""
4,KPAN_mobility-partner-oppy_MRField.conf,https://bitbucket.globaldevtools.bbva.com/bitb...,t_kpan_mobility_partner_oppy,NaN,kpan-gl-hmm-qlt-mobilitypartneroppymrfield-01....,"""18.4.3"""
25,KPAN_mobility-partner-oppy_KPAN_opportunity_MM...,https://bitbucket.globaldevtools.bbva.com/bitb...,t_kpan_mobility_partner_oppy,t_kpan_opportunity,kpan-gl-hmm-qlt-mobilitypartneroppymmrule-01.json,"""18.4.3"""
31,KPAN_mobility-partner-oppy_P68X_vehicle-versio...,https://bitbucket.globaldevtools.bbva.com/bitb...,t_kpan_mobility_partner_oppy,t_p68x_vehicle_version_catalog,kpan-gl-hmm-qlt-mobilitypartneroppymmrule-02.json,"""18.4.3"""
32,KPAN_mobility-partner-oppy_KSAN_contract-globa...,https://bitbucket.globaldevtools.bbva.com/bitb...,t_kpan_mobility_partner_oppy,t_ksan_contract_global_local,kpan-gl-hmm-qlt-mobilitypartneroppymmrule-03.json,"""18.4.3"""
0,KPAN_opportunity_MRField.conf,https://bitbucket.globaldevtools.bbva.com/bitb...,t_kpan_opportunity,NaN,kpan-gl-hmm-qlt-opportunitymrfield-01.json,"""18.4.3"""
1,KPAN_opportunity_MRObject.conf,https://bitbucket.globaldevtools.bbva.com/bitb...,t_kpan_opportunity,NaN,kpan-gl-hmm-qlt-opportunitymrobject-01.json,"""18.4.3"""
2,KPAN_opportunity_KCOG_entity_MMRule.conf,https://bitbucket.globaldevtools.bbva.com/bitb...,t_kpan_opportunity,t_kcog_entity,kpan-gl-hmm-qlt-opportunitymmrule-01.json,"""18.4.3"""
3,KPAN_opportunity_NM7R_lead_MMRule.conf,https://bitbucket.globaldevtools.bbva.com/bitb...,t_kpan_opportunity,t_nm7r_lead,kpan-gl-hmm-qlt-opportunitymmrule-02.json,"""18.4.3"""
16,KPAN_opportunity_YH2J_gbl-channel-hier-master_...,https://bitbucket.globaldevtools.bbva.com/bitb...,t_kpan_opportunity,t_yh2j_gbl_channel_hier_master,kpan-gl-hmm-qlt-opportunitymmrule-03.json,"""18.4.3"""
36,KPAN_oppy-manager-asgn_MRField.conf,https://bitbucket.globaldevtools.bbva.com/bitb...,t_kpan_oppy_manager_asgn,NaN,kpan-gl-hmm-qlt-oppymanagerasgnmrfield-01.json,"""18.4.3"""
34,KPAN_oppy-mgr-comnt_MRField.conf,https://bitbucket.globaldevtools.bbva.com/bitb...,t_kpan_oppy_mgr_comnt,NaN,kpan-gl-hmm-qlt-oppymgrcomntmrfield-01.json,"""18.4.3"""
33,KPAN_oppy-status-trcblty_MRField.conf,https://bitbucket.globaldevtools.bbva.com/bitb...,t_kpan_oppy_status_trcblty,NaN,kpan-gl-hmm-qlt-oppystatustrcbltymrfield-01.json,"""18.4.3"""
17,KPAN_person-cred-fclty-psl-dp_MRField.conf,https://bitbucket.globaldevtools.bbva.com/bitb...,t_kpan_person_cred_fclty_psl_dp,NaN,kpan-gl-hmm-qlt-personcredfcltypsldmrfield-01....,"""18.4.3"""
5,KPAN_person-cred-fclty-psl-dp_KPAN_credit-fclt...,https://bitbucket.globaldevtools.bbva.com/bitb...,t_kpan_person_cred_fclty_psl_dp,t_kpan_credit_fclty_proposals,kpan-gl-hmm-qlt-personcredfcltypsldmmrule-01.json,"""18.4.3"""
18,KPAN_person-cred-fclty-psl-dp_KCOG_country_MMR...,https://bitbucket.globaldevtools.bbva.com/bitb...,t_kpan_person_cred_fclty_psl_dp,t_kcog_country,kpan-gl-hmm-qlt-personcredfcltypsldmmrule-02.json,"""18.4.3"""
19,KPAN_person-cred-fclty-psl-dp_KCOG_currency_MM...,https://bitbucket.globaldevtools.bbva.com/bitb...,t_kpan_person_cred_fclty_psl_dp,t_kcog_currency,kpan-gl-hmm-qlt-personcredfcltypsldmmrule-03.json,"""18.4.3"""
29,KPAN_person-cred-fclty-psl-dp_KBTQ_role-person...,https://bitbucket.globaldevtools.bbva.com/bitb...,t_kpan_person_cred_fclty_psl_dp,t_kbtq_role_person,kpan-gl-hmm-qlt-personcredfcltypsldmmrule-04.json,"""18.4.3"""
20,KPAN_person-credit-fclty-psl_MRField.conf,https://bitbucket.globaldevtools.bbva.com/bitb...,t_kpan_person_credit_fclty_psl,NaN,kpan-gl-hmm-qlt-personcreditfcltypsmrfield-01....,"""18.4.3"""
37,KPAN_person-credit-fclty-psl_MRObject.conf,https://bitbucket.globaldevtools.bbva.com/bitb...,t_kpan_person_credit_fclty_psl,NaN,kpan-gl-hmm-qlt-personcreditfcltypsmrobject-01...,"""18.4.3"""
21,KPAN_person-credit-fclty-psl_KCOG_country_MMRu...,https://bitbucket.globaldevtools.bbva.com/bitb...,t_kpan_person_credit_fclty_psl,t_kcog_country,kpan-gl-hmm-qlt-personcreditfcltypsmmrule-01.json,"""18.4.3"""
22,KPAN_person-credit-fclty-psl_KCOG_currency_MMR...,https://bitbucket.globaldevtools.bbva.com/bitb...,t_kpan_person_credit_fclty_psl,t_kcog_currency,kpan-gl-hmm-qlt-personcreditfcltypsmmrule-02.json,"""18.4.3"""
27,KPAN_person-credit-fclty-psl_KBTQ_role-person_...,https://bitbucket.globaldevtools.bbva.com/bitb...,t_kpan_person_credit_fclty_psl,t_kbtq_role_person,kpan-gl-hmm-qlt-personcreditfcltypsmmrule-03.json,"""18.4.3"""
28,KPAN_person-credit-fclty-psl_KPAN_credit-fclty...,https://bitbucket.globaldevtools.bbva.com/bitb...,t_kpan_person_credit_fclty_psl,t_kpan_credit_fclty_proposals,kpan-gl-hmm-qlt-personcreditfcltypsmmrule-04.json,"""18.4.3"""

In [29]:
print("versión de subida de jobs:")
print("\n- todos:")
print(list(conf_url.version.sort_values().unique()))
print("\n- por UA:")
list((conf_url.conf.str[:4]+': '+conf_url.version).unique())

versión de subida de jobs:

- todos:
['"16.0.1"', '"16.1.5"', '"18.3.0"', '"18.3.3"', '"18.3.5"', '"18.3.6"', '"18.3.7"', '"18.3.8"', '"18.4.0"', '"18.4.1"', '"18.4.3"']

- por UA:

['B0HN: "18.3.3"',
 'CGJ7: "18.3.7"',
 'CGJ7: "18.4.0"',
 'CMOV: "18.3.0"',
 'CTAR: "18.3.3"',
 'DAST: "16.1.5"',
 'DTAU: "18.4.1"',
 'EJB6: "18.3.3"',
 'FZPD: "18.3.3"',
 'G5M3: "18.3.3"',
 'J7IL: "18.3.3"',
 'KATC: "18.3.3"',
 'KCDG: "18.3.0"',
 'KCEG: "18.3.8"',
 'KCPG: "18.3.3"',
 'KCTD: "18.3.5"',
 'KFCM: "18.4.0"',
 'KMIG: "18.3.3"',
 'KNFA: "18.3.3"',
 'KPAN: "18.4.3"',
 'KSRR: "18.3.3"',
 'KSTB: "18.3.5"',
 'KSZG: "18.3.7"',
 'KUSU: "18.3.3"',
 'KWTH: "18.3.3"',
 'L9CT: "18.4.1"',
 'L9SV: "18.3.5"',
 'MSX9: "18.3.6"',
 'NM7R: "18.3.3"',
 'NOLS: "18.3.6"',
 'P68X: "18.3.3"',
 'P6R1: "18.3.3"',
 'R4FU: "18.3.6"',
 'RE4M: "18.4.1"',
 'RZUA: "18.3.3"',
 'SCAT: "16.0.1"',
 'TDI3: "18.3.3"',
 'TLHR: "18.3.3"',
 'YFVH: "18.3.6"']