> # ATENCIÓN: 
> ## 1. Para lanzar el script el WIP debe estar consolidado o **todas las reglas deben tener versión**
> ## 2. Las reglas deben estar marcadas como **"DELIVERED"**
> Las otras reglas/confs se ignorarán
> ## 3. Se deben rellenar las UUAAs a desplegar/modificar
> Sino, se cogerán todas las UUAAs presentes en el WIP
> ## 4. Rellenar, si la hay, version_personalizada.
>Sino, se cogerá la última versión en el WIP para cada UUAA. De cara al TAG de la URL del job en la documentación  
>- Ejemplo:  
> https://bitbucket.gobaldevtools.bbva.com/bitbucket/projects/GL_B0HN_APP-ID-23103_DSG/repos/glgldh360gloqlt/browse/hammurabi/jobs/b0hn-gl-hmm-qlt-sustgroupsfdbkmmrule-03.json?at=refs%2Ftags%2Fv14.0.3  
> - En este caso, versión de subida:  
> 14.0.3

In [1]:
# !pip install --trusted-host=pypi.org --trusted-host=files.pythonhosted.org --user -U numpy 
# !pip install --trusted-host=pypi.org --trusted-host=files.pythonhosted.org --user "C:\Users\O005820\Downloads\numpy-2.2.4.tar.gz"
# !pip uninstall numpy
# !dir C:\Users\O005820\Downloads

In [2]:
import os
import shutil
import pandas as pd
import numpy as np
import json
import warnings
warnings.filterwarnings('ignore')
pd.set_option('display.max_columns', None)

IMPORTANTE: Indicamos UUAAs a modificar

In [3]:
UUAAs = [] #se cogerán todas las UUAAs del WIP

#selección de UUAAs
UUAAs = [
'B0HN',
# 'CGJ7',
# 'CMOV',
# 'CTAR',
# 'DTAU',
# 'EJB6',
# 'FZPD',
'G5M3',
# 'J7IL',
# 'KATC',
# 'KCEG',
# 'KCPG',
# 'KCTD',
'KCDG'
# 'KFCM',
# 'KMIG',
# 'KNFA',
# 'KPAN',
# 'KSRR',
# 'KSTB',
# 'KSZG',
# 'KUSU',
# 'KWTH',
# 'L9CT',
# 'L9SV',
# 'MSX9',
# 'NM7R',
# 'NOLS',
# 'P68X',
# 'P6R1',
# 'R4FU',
# 'RE4M',
# 'RZUA',
# 'SCAT',
# 'TDI3',
# 'TLHR',
# 'YFVH',
]

version_personalizada = "" #RELLENAR EN ACTUALIZACIONES MASIVAS: versión de subida de jobs (si no es para todos la misma, dejarlo vacío y cogerá la ultima versión del wip para cada UUAA)

if not UUAAs:
    print('UUAAs no declaradas (UUAAs = [])\n-> Se actualizarán todas las UUAAs presentes en el WIP con reglas DELIVERED,\nversión',version_personalizada)
else:
    UUAAs = [i.lower() for i in UUAAs]
    print('UUAAs declaradas\n-> Se actualizarán las siguientes UUAAs')
    print(UUAAs)

UUAAs declaradas
-> Se actualizarán las siguientes UUAAs
['b0hn', 'g5m3', 'kcdg']

In [4]:
dict_tablas = {
    # 't_tdi3_cust_promo_adhesion_dp':'a',
    # 't_re4m_virtual_assistant_message':'b'
}

Confs

In [5]:
extralib_job_eur = {
    "jobName": "test",
    "description": "test",
    "size": "XS",
    "runtime": "hammurabi-lts",
    "streaming": False,
    "params": {
        "metaConfig": "gl:re4m:glgldh360gloqlt:RE4M_physical-interaction_MRField:14.0.7",
        "extraLibs": "s3://ada-eu-south-2-core-live-artifacts/dataproc/migration-artifacts/artifactory/gl-datio-spark-libs-maven-local/com/bbva/projectsdatio/c360hammcustom/1.3.4/c360hammcustom-1.3.4-jar-with-dependencies.jar" 
    },
    "env": {
        "XD_ENABLED":"true"
    },
    "tags": [ #https://docs.google.com/document/d/1nTowUue9ahe3-T69lvLM_vASvvfrueJz9qek2cYwwrk/edit?tab=t.0
        "sdm",
        "360",
        "cs",
        "gl",
        "qlt",
        "global",
        "master",
        "SDATOOL-49915"
    ],
    "kind": "processing",
    "concurrency": 10
}

In [6]:
other_job_eur = {
    "jobName": "test",
    "description": "test",
    "size": "XS",
    "runtime": "hammurabi-lts",
    "streaming": False,
    "params": {
        "metaConfig": "gl:re4m:glgldh360gloqlt:RE4M_physical-interaction_MRField:14.0.7",
    },
    "env": {
        "XD_ENABLED":"true"
    },
    "tags": [
        "sdm",
        "360",
        "cs",
        "gl",
        "qlt",
        "global",
        "master",
        "SDATOOL-49915"
    ],
    "kind": "processing",
    "concurrency": 10
}

In [7]:
extralib_job_ame = {
        "_id": "test",
        "description": "test",
        "size": "XS",
        "runtime": "hammurabi-lts",
        "streaming": False,
        "params": {
                "configUrl": "https://artifactory-gdt.central-01.nextgen.igrupobbva/artifactory/gl-datio-spark-libs-maven-dev-local/com/datiobd/c360-hammurabi/99.9.9-PR-351-SNAPSHOT/entregable_hammurabi/L9CT/L9CT_grp-clnt-cmpny-crbn-data_CIB_MRField.conf",
                "repoSecurity": "artifactory",
                "sparkHistoryEnabled": "false",
                "extraLibs": "https://artifactory-gdt.central-01.nextgen.igrupobbva/artifactory/gl-datio-spark-libs-maven-local/com/bbva/gdh/hammurabi-maxminfilter/1.2.0/hammurabi-maxminfilter-1.2.0-jar-with-dependencies.jar"
        },
        "env": {
                "XD_ENABLED":"true"
        },
        "tags": [
        "sdm",
        "360",
        "cs",
        "gl",
        "qlt",
        "global",
        "master",
        "SDATOOL-49915"
        ],
        "kind": "processing"
}

In [8]:
other_job_ame = {
    "_id": "test",
    "description": "test",
    "size": "XS",
    "runtime": "hammurabi-lts",
    "streaming": False,
    "params": {
        "configUrl": "https://artifactory-gdt.central-01.nextgen.igrupobbva/artifactory/gl-datio-spark-libs-maven-dev-local/com/datiobd/c360-hammurabi/12.1.0-PR-321-SNAPSHOT/entregable_hammurabi/KCDG/KCDG_graph-edges_KCDG_graph-nodes_MMRule.conf",
        "repoSecurity": "artifactory",
        "sparkHistoryEnabled": "false"
    },
    "env": {
        "XD_ENABLED":"true"
    },
    "tags": [
        "sdm",
        "360",
        "cs",
        "gl",
        "qlt",
        "global",
        "master",
        "SDATOOL-49915"
    ],
    "kind": "processing"
}

WIP confs

In [9]:
cols = ['UUAA','STATUS IMPLANTATION','TABLE (en C360)','Secondary Table (4.3-5.2-6.4)','Conf (MRField, ORField, OCField,...)', 'Conf name', 'version  FINISHED','Url conf\nv13.0.4 (new)','Url Extralibs','IMPLANTATION TYPE']
wip = pd.read_csv('wip_final.csv', header=1)[cols].dropna(subset='version  FINISHED')
wip = wip[wip['STATUS IMPLANTATION']=="DELIVERED"]

wip['version_simple'] = wip['version  FINISHED'].str.replace("5.0.15","5.0.1").str.replace(".","").astype(int)
wip['unique_id'] = wip['TABLE (en C360)'].str[6:].str.replace('_','').str[:19] + wip['Conf name'].str.lower().str.split('-').str[-1].str.split('.').str[0]
wip['NombreJob'] = wip['UUAA'].str[:4].str.lower() + '-' + 'gl' + '-' + 'hmm' + '-' + 'qlt' + '-' + wip['unique_id'] + '-'
wip.sort_values(['version_simple','Url Extralibs','version_simple'], inplace=True, ascending=False)
wip.drop_duplicates(subset=['Conf name','version_simple'], inplace=True)
wip.reset_index(drop=True,inplace=True)
print(wip.columns)
print('\nNULOS:\n-----------')
print(wip.isnull().sum())
wip.columns = ['ua','status_implantation','table','secundary_table','conf_type','conf','version','ConfigURL','Extralibs','implantation','version_simple','unique_id','NombreJob']
wip = wip[wip.conf.str.contains('-qlm-')]
wip['len_unique_id'] = wip.unique_id.str.len()
wip.tail(2)

Index(['UUAA', 'STATUS IMPLANTATION', 'TABLE (en C360)',
       'Secondary Table (4.3-5.2-6.4)', 'Conf (MRField, ORField, OCField,...)',
       'Conf name', 'version  FINISHED', 'Url conf\nv13.0.4 (new)',
       'Url Extralibs', 'IMPLANTATION TYPE', 'version_simple', 'unique_id',
       'NombreJob'],
      dtype='object')

NULOS:
-----------
UUAA                                       0
STATUS IMPLANTATION                        0
TABLE (en C360)                            0
Secondary Table (4.3-5.2-6.4)            806
Conf (MRField, ORField, OCField,...)    1165
Conf name                                  0
version  FINISHED                          0
Url conf\nv13.0.4 (new)                    0
Url Extralibs                           1149
IMPLANTATION TYPE                         11
version_simple                             0
unique_id                                  0
NombreJob                                  0
dtype: int64

,ua,status_implantation,table,secundary_table,conf_type,conf,version,ConfigURL,Extralibs,implantation,version_simple,unique_id,NombreJob,len_unique_id
6,B0HN,DELIVERED,t_b0hn_toolkit_esg_rating,NaN,NaN,t_b0hn_toolkit_esg_rating-qlm-MRField.conf,19.0.0,https://artifactory.globaldevtools.bbva.com/ui...,NaN,Holding,1900,toolkitesgratingmrfield,b0hn-gl-hmm-qlt-toolkitesgratingmrfield-,23
7,B0HN,DELIVERED,t_b0hn_toolkit_esg_sector,NaN,NaN,t_b0hn_toolkit_esg_sector-qlm-MRField.conf,19.0.0,https://artifactory.globaldevtools.bbva.com/ui...,NaN,Holding,1900,toolkitesgsectormrfield,b0hn-gl-hmm-qlt-toolkitesgsectormrfield-,23

In [10]:
wip['table'].map(dict_tablas).fillna('')

0
1
2
3
4
5
6
7
Name: table, dtype: object

In [11]:
version = wip.sort_values('version_simple',ascending=False).version.unique()
print(version)

['19.0.0']

No puede ser mayor a 27

In [12]:
print(wip[wip.conf.str.contains("-qlm-")]['len_unique_id'].max())
# wip[wip.conf.str.contains("-qlm-")][['unique_id','len_unique_id','conf']].sort_values(by='len_unique_id',ascending=False)

26

In [13]:
wip_confs = wip.sort_values(by='version_simple',ascending=False)[['implantation','conf','ConfigURL','Extralibs','NombreJob','version','version_simple','ua']]

wip_confs['Extralibs'] = np.where(
    wip_confs['conf'].duplicated(keep=False),
    wip_confs.merge(wip_confs.dropna(subset=['conf','Extralibs']).rename(columns={'Extralibs':'Extralibs1'}).drop_duplicates('conf'),how='left', on='conf').Extralibs1,
    wip_confs['Extralibs']
    )

wip_confs = wip_confs.drop_duplicates(subset=['conf']).reset_index(drop=True)

wip_confs['NombreJobFinal'] = np.where(
    wip_confs['NombreJob'].duplicated(keep=False),
    wip_confs['NombreJob'] + '0' + wip_confs.groupby('NombreJob').cumcount().add(1).astype(str).str[-2:],
    wip_confs['NombreJob'] + '01'
    )
wip_confs = wip_confs.drop(columns=['NombreJob'])
wip_confs['UA'] = wip_confs['ua'].str.lower()
wip_confs['len_NombreJobFinal'] = wip_confs.NombreJobFinal.str.len()

if not UUAAs:
    UUAAs = list(wip_confs.conf.str[:4].str.lower().sort_values().unique())
wip_confs.query('UA == @UUAAs', inplace=True) #nos quedamos con nuestras UUAAs

wip_confs

,implantation,conf,ConfigURL,Extralibs,version,version_simple,ua,NombreJobFinal,UA,len_NombreJobFinal
0,Local,t_g5m3_sust_mob_operations-qlm-MRField.conf,https://artifactory.globaldevtools.bbva.com/ui...,NaN,19.0.0,1900,G5M3,g5m3-gl-hmm-qlt-sustmoboperationsmrfield-01,g5m3,43
1,Local,t_kcdg_graph_nodes-qlm-MRField.conf,https://artifactory.globaldevtools.bbva.com/ui...,NaN,19.0.0,1900,KCDG,kcdg-gl-hmm-qlt-graphnodesmrfield-01,kcdg,36
2,Holding,t_b0hn_toolkit_esg_strategy-qlm-MRField.conf,https://artifactory.globaldevtools.bbva.com/ui...,NaN,19.0.0,1900,B0HN,b0hn-gl-hmm-qlt-toolkitesgstrategymrfield-01,b0hn,44
3,Holding,t_b0hn_toolkit_ems_metric_target-qlm-MRField.conf,https://artifactory.globaldevtools.bbva.com/ui...,NaN,19.0.0,1900,B0HN,b0hn-gl-hmm-qlt-toolkitemsmetrictarmrfield-01,b0hn,45
4,Holding,t_b0hn_toolkit_esg_top_5_geo-qlm-MRField.conf,https://artifactory.globaldevtools.bbva.com/ui...,NaN,19.0.0,1900,B0HN,b0hn-gl-hmm-qlt-toolkitesgtop5geomrfield-01,b0hn,43
5,Holding,t_b0hn_toolkit_esg_general_data-qlm-MRField.conf,https://artifactory.globaldevtools.bbva.com/ui...,NaN,19.0.0,1900,B0HN,b0hn-gl-hmm-qlt-toolkitesggeneraldamrfield-01,b0hn,45
6,Holding,t_b0hn_toolkit_esg_rating-qlm-MRField.conf,https://artifactory.globaldevtools.bbva.com/ui...,NaN,19.0.0,1900,B0HN,b0hn-gl-hmm-qlt-toolkitesgratingmrfield-01,b0hn,42
7,Holding,t_b0hn_toolkit_esg_sector-qlm-MRField.conf,https://artifactory.globaldevtools.bbva.com/ui...,NaN,19.0.0,1900,B0HN,b0hn-gl-hmm-qlt-toolkitesgsectormrfield-01,b0hn,42

In [14]:
print(set(wip_confs.UA.unique()))
print('\n¿Mismas UUAAs? en wip_confs:')

print(set(wip_confs.UA.unique()) == set(UUAAs))

{'b0hn', 'g5m3', 'kcdg'}

¿Mismas UUAAs? en wip_confs:
True

No puede ser mayor a 41+5 separadores: 46

In [15]:
print(wip_confs['len_NombreJobFinal'].max())

45

Revisamos ramas de cada directorio y creamos directorios

In [16]:
#Revisamos rama de cada directorio
ruta_confs = "C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs_GITHUB/{}/gl-cs-360-gdh-qlt-{}/"
ramas = []
print(UUAAs)
for UA in UUAAs:
    print('- ',UA)
    ruta_ua = ruta_confs.format(UA,UA)
    git = 'git -C {0} rev-parse --abbrev-ref HEAD'.format(ruta_ua)
    rama = str(os.popen(git).read()).strip()
    ramas.append(rama)
    print(rama)
    # if not os.path.exists(ruta_ua+'/hammurabi/jobs/'):
    #     os.makedirs(ruta_ua+'/hammurabi/jobs/')

['b0hn', 'g5m3', 'kcdg']
-  b0hn
feature/MVP_2Q26_c360_07_04_2026
-  g5m3
feature/MVP_2Q26_c360_07_04_2026
-  kcdg
feature/MVP_2Q26_c360_07_04_2026

In [17]:
print('ramas unicas (siempre debemos actuar sobre una)')
print(list(np.unique(ramas)))

ramas unicas (siempre debemos actuar sobre una)
[np.str_('feature/MVP_2Q26_c360_07_04_2026')]

In [18]:
#Reseteamos directorios (eliminamos y volvemos a crear)
ruta_confs = "C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs_GITHUB/{}/gl-cs-360-gdh-qlt-{}/"
geo_ruta_dict = {
    'europa': '01',
    'america-ada':'02'
    }
print(UUAAs)
for UA in UUAAs:
    print(UA)
    ruta_ua = ruta_confs.format(UA,UA)
    shutil.rmtree(ruta_ua+'/hammurabi/jobs/')
    for geo_ruta in geo_ruta_dict.keys():
        os.makedirs(ruta_ua+'/hammurabi/jobs/'+geo_ruta)

['b0hn', 'g5m3', 'kcdg']
b0hn
g5m3
kcdg

Creamos jobs en cada directorio

In [19]:
version_desplegada_UA = wip_confs.sort_values('version_simple',ascending=False).drop_duplicates('UA')[['UA','version']].rename(columns={'version':'version_despliegue'})
wip_confs = wip_confs.merge(version_desplegada_UA,how='left',on='UA')
version_desplegada_UA

     UA version_despliegue
0  g5m3             19.0.0
1  kcdg             19.0.0
2  b0hn             19.0.0

In [20]:
print("mismas uuaas? \nversion_desplegada_UA")

set(version_desplegada_UA.UA) == set(UUAAs)

mismas uuaas?
version_desplegada_UA

True

In [21]:
print('UUAAs afectadas:')
print(sorted(set(wip_confs.UA.unique())))
print("\nmismas uuaas? \nwip_confs")

set(wip_confs.UA.unique()) == set(UUAAs)

UUAAs afectadas:
['b0hn', 'g5m3', 'kcdg']

mismas uuaas?
wip_confs

True

In [22]:
extralib_confs = wip_confs.dropna(subset='Extralibs')
other_confs = wip_confs[wip_confs.Extralibs.isnull()]

In [23]:
#SI HEMOS CREADO UN NUEVO REPO INCLUIR EN './repos/repos.csv' desde https://docs.google.com/spreadsheets/d/1aLELrHoXPwm8CSY2a6DN6DRqoIkruHQO37JrQcaZFNM/edit?gid=1588638166#gid=1588638166
uuaas_repos = pd.read_csv('./repos/repos.csv')
uuaas_repos.UUAA = uuaas_repos.UUAA.str.lower()
uuaas_repos.index = uuaas_repos.UUAA
dict_project_ua = uuaas_repos.project.to_dict()

In [24]:
for ua in UUAAs:
    print(ua,'- ¿Está en el inventario de repos? ("repos\\repos.csv"):\n', ua in list(uuaas_repos.UUAA))
    if not ua in list(uuaas_repos.UUAA):
        print("\t¡ATENCIÓN! Añadir UA {0} a 'repos\\repos.csv'".format(ua))

b0hn - ¿Está en el inventario de repos? ("repos\repos.csv"):
 True
g5m3 - ¿Está en el inventario de repos? ("repos\repos.csv"):
 True
kcdg - ¿Está en el inventario de repos? ("repos\repos.csv"):
 True

In [25]:
geo_ruta_dict

{'europa': '01', 'america-ada': '02'}

In [26]:
geos = ["gl"]#,"es","co","pe","ar","mx"]
conf_job_dict = {}
#Extralibs
for index, row in extralib_confs.iterrows():
    for geo in geos:
        for geo_ruta in geo_ruta_dict.keys():
            if row["implantation"]=="Holding":
                geo = "gl"
            nombre_job = row['NombreJobFinal']
            nombre_job = nombre_job[0:5] + geo + nombre_job[7:]
            ruta_ua = ruta_confs.format(row['UA'],row['UA'])
            if geo_ruta == 'europa': #para europa, nuevo formato ADA
                extralib_job_eur['description'] = nombre_job
                extralib_job_eur['jobName'] = nombre_job
                extralib_job_eur['params']['metaConfig'] = "gl:" + row['UA'] + ":" + "gl-cs-360-gdh-qlt-"+row['UA'] + ":" + row['conf'].replace('.conf','') + ":" + row['version']
                extralib_job_eur['params']['extraLibs'] = row['Extralibs'].replace('https://artifactory.globaldevtools.bbva.com/ui/repos/tree/General/','s3://ada-eu-south-2-core-live-artifacts/dataproc/migration-artifacts/artifactory/'.format(geo_ruta_dict[geo_ruta]))
                extralib_job_eur['params']['extraLibs'] = row['Extralibs'].replace('https://artifactory-gdt.central-01.nextgen.igrupobbva/artifactory/','s3://ada-eu-south-2-core-live-artifacts/dataproc/migration-artifacts/artifactory/'.format(geo_ruta_dict[geo_ruta]))
                extralib_job = extralib_job_eur
            elif geo_ruta == 'america-ada': #para america-ada, nuevo formato ADA
                nombre_job_ada = row['NombreJobFinal']
                extralib_job_eur['description'] = nombre_job
                extralib_job_eur['jobName'] = nombre_job
                extralib_job_eur['params']['metaConfig'] = "gl:" + row['UA'] + ":" + "gl-cs-360-gdh-qlt-"+row['UA'] + ":" + row['conf'].replace('.conf','') + ":" + row['version']
                extralib_job_eur['params']['extraLibs'] = row['Extralibs'].replace('https://artifactory.globaldevtools.bbva.com/ui/repos/tree/General/','s3://ada-us-east-1-core-live-artifacts/dataproc/migration-artifacts/artifactory/'.format(geo_ruta_dict[geo_ruta]))
                extralib_job_eur['params']['extraLibs'] = row['Extralibs'].replace('https://artifactory-gdt.central-01.nextgen.igrupobbva/artifactory/','s3://ada-us-east-1-core-live-artifacts/dataproc/migration-artifacts/artifactory/'.format(geo_ruta_dict[geo_ruta]))
                extralib_job = extralib_job_eur
            with open(ruta_ua + '/hammurabi/jobs/' + geo_ruta + '/' + nombre_job + '.json', 'w', encoding='utf-8') as f:
                json.dump(extralib_job, f, ensure_ascii=False, indent=4)
            print(ruta_ua + '/hammurabi/jobs/' + geo_ruta + '/' + nombre_job + '.json')
            
        if not version_personalizada:
            # conf_job_dict[row['conf']] = (
            #     "https://bitbucket.globaldevtools.bbva.com/bitbucket/projects/" + dict_project_ua[row['UA']] + "/repos/glgldh360gloqlt/browse/hammurabi/jobs/"+list(geo_ruta_dict.keys())[0]+'/'+nombre_job+".json"+"?at=refs%2Ftags%2Fv"+row['version_despliegue'] + "\n"
            #     "https://bitbucket.globaldevtools.bbva.com/bitbucket/projects/" + dict_project_ua[row['UA']] + "/repos/glgldh360gloqlt/browse/hammurabi/jobs/"+list(geo_ruta_dict.keys())[1]+'/'+nombre_job+".json"+"?at=refs%2Ftags%2Fv"+row['version_despliegue']
            #     )
            conf_job_dict[row['conf']] = (
                "https://bbva.ghe.com/platform/gl-cs-360-gdh-qlt-"+ row['UA']+ "/blob/" + row['version_despliegue'] + "/hammurabi/jobs/"+ list(geo_ruta_dict.keys())[0] +nombre_job+".json" + "\n"
                "https://bbva.ghe.com/platform/gl-cs-360-gdh-qlt-"+ row['UA']+ "/blob/" + row['version_despliegue'] + "/hammurabi/jobs/"+ list(geo_ruta_dict.keys())[1] +nombre_job+".json"
                )
        else:
            # conf_job_dict[row['conf']] = (
            #     "https://bitbucket.globaldevtools.bbva.com/bitbucket/projects/" + dict_project_ua[row['UA']] + "/repos/glgldh360gloqlt/browse/hammurabi/jobs/"+list(geo_ruta_dict.keys())[0]+'/'+nombre_job+".json"+"?at=refs%2Ftags%2Fv"+version_personalizada + "\n"
            #     "https://bitbucket.globaldevtools.bbva.com/bitbucket/projects/" + dict_project_ua[row['UA']] + "/repos/glgldh360gloqlt/browse/hammurabi/jobs/"+list(geo_ruta_dict.keys())[1]+'/'+nombre_job+".json"+"?at=refs%2Ftags%2Fv"+version_personalizada   
            #     )
            conf_job_dict[row['conf']] = (
                "https://bbva.ghe.com/platform/gl-cs-360-gdh-qlt-"+ row['UA']+ "/blob/" + version_personalizada + "/hammurabi/jobs/"+ list(geo_ruta_dict.keys())[0] +nombre_job+".json" + "\n"
                "https://bbva.ghe.com/platform/gl-cs-360-gdh-qlt-"+ row['UA']+ "/blob/" + version_personalizada + "/hammurabi/jobs/"+ list(geo_ruta_dict.keys())[1] +nombre_job+".json"
                )

#Others
for index, row in other_confs.iterrows():
    for geo in geos:
        for geo_ruta in geo_ruta_dict.keys():
            if row["implantation"]=="Holding":
                geo = "gl"
            nombre_job = row['NombreJobFinal']
            nombre_job = nombre_job[0:5] + geo + nombre_job[7:]
            ruta_ua = ruta_confs.format(row['UA'],row['UA'])
            if geo_ruta == 'europa':        #para europa, nuevo formato ADA
                other_job_eur['description'] = nombre_job
                other_job_eur['jobName'] = nombre_job
                other_job_eur['params']['metaConfig'] = "gl:" + row['UA'] + ":" + "gl-cs-360-gdh-qlt-"+row['UA'] + ":" + row['conf'].replace('.conf','') + ":" + row['version']
                other_job = other_job_eur
            elif geo_ruta == 'america-ada': #para europa, nuevo formato ADA
                nombre_job = row['NombreJobFinal']
                other_job_eur['description'] = nombre_job
                other_job_eur['jobName'] = nombre_job
                other_job_eur['params']['metaConfig'] = "gl:" + row['UA'] + ":" + "gl-cs-360-gdh-qlt-"+row['UA'] + ":" + row['conf'].replace('.conf','') + ":" + row['version']
                other_job = other_job_eur
            with open(ruta_ua + '/hammurabi/jobs/' + geo_ruta + '/' + nombre_job + '.json', 'w', encoding='utf-8') as f:
                json.dump(other_job, f, ensure_ascii=False, indent=4)
            print(ruta_ua + '/hammurabi/jobs/' + geo_ruta + '/' + nombre_job + '.json')

        if not version_personalizada:
            conf_job_dict[row['conf']] = (
                "https://bbva.ghe.com/platform/gl-cs-360-gdh-qlt-"+ row['UA']+ "/blob/" + row['version_despliegue'] + "/hammurabi/jobs/"+ list(geo_ruta_dict.keys())[0]+ "/" + nombre_job+".json" + "\n"
                "https://bbva.ghe.com/platform/gl-cs-360-gdh-qlt-"+ row['UA']+ "/blob/" + row['version_despliegue'] + "/hammurabi/jobs/"+ list(geo_ruta_dict.keys())[1]+ "/" + nombre_job+".json"
                )
        else:
            conf_job_dict[row['conf']] = (
                "https://bbva.ghe.com/platform/gl-cs-360-gdh-qlt-"+ row['UA']+ "/blob/" + version_personalizada + "/hammurabi/jobs/"+ list(geo_ruta_dict.keys())[0]+ "/" + nombre_job+".json" + "\n"
                "https://bbva.ghe.com/platform/gl-cs-360-gdh-qlt-"+ row['UA']+ "/blob/" + version_personalizada + "/hammurabi/jobs/"+ list(geo_ruta_dict.keys())[1]+ "/" + nombre_job+".json"
                )

C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs_GITHUB/g5m3/gl-cs-360-gdh-qlt-g5m3//hammurabi/jobs/europa/g5m3-gl-hmm-qlt-sustmoboperationsmrfield-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs_GITHUB/g5m3/gl-cs-360-gdh-qlt-g5m3//hammurabi/jobs/america-ada/g5m3-gl-hmm-qlt-sustmoboperationsmrfield-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs_GITHUB/kcdg/gl-cs-360-gdh-qlt-kcdg//hammurabi/jobs/europa/kcdg-gl-hmm-qlt-graphnodesmrfield-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs_GITHUB/kcdg/gl-cs-360-gdh-qlt-kcdg//hammurabi/jobs/america-ada/kcdg-gl-hmm-qlt-graphnodesmrfield-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs_GITHUB/b0hn/gl-cs-360-gdh-qlt-b0hn//hammurabi/jobs/europa/b0hn-gl-hmm-qlt-toolkitesgstrategymrfield-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs_GITHUB/b0hn/gl-cs-360-gdh-qlt-b0hn//hammurabi/jobs/america-ada/b0hn-gl-hmm-qlt-toolkitesgstrategymrfield-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs_GITHUB/b0hn/gl-cs-360-gdh-qlt-b0hn//hammurabi/jobs/europa/b0hn-gl-hmm-qlt-toolkitemsmetrictarmrfield-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs_GITHUB/b0hn/gl-cs-360-gdh-qlt-b0hn//hammurabi/jobs/america-ada/b0hn-gl-hmm-qlt-toolkitemsmetrictarmrfield-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs_GITHUB/b0hn/gl-cs-360-gdh-qlt-b0hn//hammurabi/jobs/europa/b0hn-gl-hmm-qlt-toolkitesgtop5geomrfield-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs_GITHUB/b0hn/gl-cs-360-gdh-qlt-b0hn//hammurabi/jobs/america-ada/b0hn-gl-hmm-qlt-toolkitesgtop5geomrfield-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs_GITHUB/b0hn/gl-cs-360-gdh-qlt-b0hn//hammurabi/jobs/europa/b0hn-gl-hmm-qlt-toolkitesggeneraldamrfield-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs_GITHUB/b0hn/gl-cs-360-gdh-qlt-b0hn//hammurabi/jobs/america-ada/b0hn-gl-hmm-qlt-toolkitesggeneraldamrfield-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs_GITHUB/b0hn/gl-cs-360-gdh-qlt-b0hn//hammurabi/jobs/europa/b0hn-gl-hmm-qlt-toolkitesgratingmrfield-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs_GITHUB/b0hn/gl-cs-360-gdh-qlt-b0hn//hammurabi/jobs/america-ada/b0hn-gl-hmm-qlt-toolkitesgratingmrfield-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs_GITHUB/b0hn/gl-cs-360-gdh-qlt-b0hn//hammurabi/jobs/europa/b0hn-gl-hmm-qlt-toolkitesgsectormrfield-01.json
C:/Users/O005820/Documents/repositorios/GDH_c360_hammurabi_UUAAs_GITHUB/b0hn/gl-cs-360-gdh-qlt-b0hn//hammurabi/jobs/america-ada/b0hn-gl-hmm-qlt-toolkitesgsectormrfield-01.json

In [27]:
conf_url_OLD = pd.read_csv('wip_conf_url_OLD.csv',sep=',')
conf_url_OLD['UA'] = conf_url_OLD.conf.str[:4].str.lower()
conf_url_OLD.query('UA != @UUAAs',inplace=True)
print("UUAAs NO afectadas:\n",list(conf_url_OLD.UA.sort_values().unique()))
print("UUAAs SI afectadas:\n",UUAAs)
#personalizar eliminación
# conf_url_OLD.query('UA != "ksci"',inplace=True)
conf_url_OLD.drop(columns='UA',inplace=True)

conf_url_OLD

UUAAs NO afectadas:
 ['cgj7', 'cmov', 'ctar', 'dast', 'dtau', 'ejb6', 'fzpd', 'j7il', 'katc', 'kceg', 'kcpg', 'kctd', 'kfcm', 'kmig', 'knfa', 'kpan', 'ksrr', 'kstb', 'kszg', 'kusu', 'kwth', 'l9ct', 'l9sv', 'msx9', 'nm7r', 'nols', 'p68x', 'p6r1', 'r4fu', 're4m', 'rzua', 'scat', 'tdi3', 'tlhr', 'yfvh']
UUAAs SI afectadas:
 ['b0hn', 'g5m3', 'kcdg']

,conf,job_url,table,secundary_table,job,version
17,CGJ7_customer-carbon-footprint_MRField.conf,https://bitbucket.globaldevtools.bbva.com/bitb...,t_cgj7_customer_carbon_footprint,NaN,cgj7-gl-hmm-qlt-customercarbonfootpmrfield-01....,"""18.3.7"""
18,CGJ7_customer-carbon-footprint_MRObject.conf,https://bitbucket.globaldevtools.bbva.com/bitb...,t_cgj7_customer_carbon_footprint,NaN,cgj7-gl-hmm-qlt-customercarbonfootpmrobject-01...,"""18.3.7"""
19,CGJ7_customer-carbon-footprint_KCOG_country_MM...,https://bitbucket.globaldevtools.bbva.com/bitb...,t_cgj7_customer_carbon_footprint,t_kcog_country,cgj7-gl-hmm-qlt-customercarbonfootpmmrule-01.json,"""18.3.7"""
20,CGJ7_customer-carbon-footprint_KBTQ_customer-i...,https://bitbucket.globaldevtools.bbva.com/bitb...,t_cgj7_customer_carbon_footprint,t_kbtq_customer_info,cgj7-gl-hmm-qlt-customercarbonfootpmmrule-02.json,"""18.3.7"""
21,CGJ7_customer-carbon-footprint_KCOG_entity_MMR...,https://bitbucket.globaldevtools.bbva.com/bitb...,t_cgj7_customer_carbon_footprint,t_kcog_entity,cgj7-gl-hmm-qlt-customercarbonfootpmmrule-03.json,"""18.3.7"""
...,...,...,...,...,...,...
887,TDI3_tracking-code_L9SV_placement-display_MMRu...,https://bitbucket.globaldevtools.bbva.com/bitb...,t_tdi3_tracking_code,t_l9sv_placement_display,tdi3-gl-hmm-qlt-trackingcodemmrule-01.json,"""18.3.3"""
888,TDI3_tracking-code_TDI3_communication_MMRule.conf,https://bitbucket.globaldevtools.bbva.com/bitb...,t_tdi3_tracking_code,t_tdi3_communication,tdi3-gl-hmm-qlt-trackingcodemmrule-02.json,"""18.3.3"""
889,TLHR_complaints-claims_MRField.conf,https://bitbucket.globaldevtools.bbva.com/bitb...,t_tlhr_complaints_claims,NaN,tlhr-gl-hmm-qlt-complaintsclaimsmrfield-01.json,"""18.3.3"""
890,TLHR_complaints-claims_MRObject.conf,https://bitbucket.globaldevtools.bbva.com/bitb...,t_tlhr_complaints_claims,NaN,tlhr-gl-hmm-qlt-complaintsclaimsmrobject-01.json,"""18.3.3"""
891,YFVH_cards-calc-balances_MRField.conf,https://bitbucket.globaldevtools.bbva.com/bitb...,t_yfvh_cards_calc_balances,NaN,yfvh-gl-hmm-qlt-cardscalcbalancesmrfield-01.json,"""18.3.6"""

In [30]:
conf_url_NEW = pd.DataFrame(conf_job_dict.items(), columns=['conf', 'job_url']).merge(wip[['table','secundary_table','conf']].drop_duplicates(subset='conf').dropna(subset=['table','conf']),how='left',on='conf')
conf_url_NEW['job'] = conf_url_NEW.job_url.apply(lambda x: x.split('/')[-1])
conf_url_NEW['job'] = conf_url_NEW.job.apply(lambda x: x.split('?')[0])
# conf_url_NEW['version'] = conf_url_NEW.job_url.str[-6:]
conf_url_NEW['version'] = conf_url_NEW.job_url.apply(lambda x:str(x).split('/blob/')[2].split('/hammurabi/')[0])
conf_url = pd.concat([conf_url_OLD,conf_url_NEW],axis=0)
conf_url['version'] = '"' + conf_url['version'].str.replace('"','') + '"'
conf_url['type'] = conf_url.conf.str.extract(r'_(.{6,8}).conf').replace({'MRField':1, 'MRObject':2, 'MMRule':3})
conf_url.sort_values(['table','type'], inplace=True)
conf_url.drop(columns='type', inplace=True)
conf_url.to_csv('wip_conf_url_NEW.csv',sep=';',index=False)
conf_url

,conf,job_url,table,secundary_table,job,version
3,t_b0hn_toolkit_ems_metric_target-qlm-MRField.conf,https://bbva.ghe.com/platform/gl-cs-360-gdh-ql...,t_b0hn_toolkit_ems_metric_target,NaN,b0hn-gl-hmm-qlt-toolkitemsmetrictarmrfield-01....,"""19.0.0"""
5,t_b0hn_toolkit_esg_general_data-qlm-MRField.conf,https://bbva.ghe.com/platform/gl-cs-360-gdh-ql...,t_b0hn_toolkit_esg_general_data,NaN,b0hn-gl-hmm-qlt-toolkitesggeneraldamrfield-01....,"""19.0.0"""
6,t_b0hn_toolkit_esg_rating-qlm-MRField.conf,https://bbva.ghe.com/platform/gl-cs-360-gdh-ql...,t_b0hn_toolkit_esg_rating,NaN,b0hn-gl-hmm-qlt-toolkitesgratingmrfield-01.json,"""19.0.0"""
7,t_b0hn_toolkit_esg_sector-qlm-MRField.conf,https://bbva.ghe.com/platform/gl-cs-360-gdh-ql...,t_b0hn_toolkit_esg_sector,NaN,b0hn-gl-hmm-qlt-toolkitesgsectormrfield-01.json,"""19.0.0"""
2,t_b0hn_toolkit_esg_strategy-qlm-MRField.conf,https://bbva.ghe.com/platform/gl-cs-360-gdh-ql...,t_b0hn_toolkit_esg_strategy,NaN,b0hn-gl-hmm-qlt-toolkitesgstrategymrfield-01.json,"""19.0.0"""
...,...,...,...,...,...,...
887,TDI3_tracking-code_L9SV_placement-display_MMRu...,https://bitbucket.globaldevtools.bbva.com/bitb...,t_tdi3_tracking_code,t_l9sv_placement_display,tdi3-gl-hmm-qlt-trackingcodemmrule-01.json,"""18.3.3"""
888,TDI3_tracking-code_TDI3_communication_MMRule.conf,https://bitbucket.globaldevtools.bbva.com/bitb...,t_tdi3_tracking_code,t_tdi3_communication,tdi3-gl-hmm-qlt-trackingcodemmrule-02.json,"""18.3.3"""
889,TLHR_complaints-claims_MRField.conf,https://bitbucket.globaldevtools.bbva.com/bitb...,t_tlhr_complaints_claims,NaN,tlhr-gl-hmm-qlt-complaintsclaimsmrfield-01.json,"""18.3.3"""
890,TLHR_complaints-claims_MRObject.conf,https://bitbucket.globaldevtools.bbva.com/bitb...,t_tlhr_complaints_claims,NaN,tlhr-gl-hmm-qlt-complaintsclaimsmrobject-01.json,"""18.3.3"""
891,YFVH_cards-calc-balances_MRField.conf,https://bitbucket.globaldevtools.bbva.com/bitb...,t_yfvh_cards_calc_balances,NaN,yfvh-gl-hmm-qlt-cardscalcbalancesmrfield-01.json,"""18.3.6"""

In [32]:
version = '"19.0.0"'
print('uuaas:',conf_url[conf_url.version == version].job.str[:4].unique())
conf_url_version = conf_url[conf_url.version == version]
conf_url_version

uuaas: ['b0hn' 'g5m3' 'kcdg']

,conf,job_url,table,secundary_table,job,version
3,t_b0hn_toolkit_ems_metric_target-qlm-MRField.conf,https://bbva.ghe.com/platform/gl-cs-360-gdh-ql...,t_b0hn_toolkit_ems_metric_target,NaN,b0hn-gl-hmm-qlt-toolkitemsmetrictarmrfield-01....,"""19.0.0"""
5,t_b0hn_toolkit_esg_general_data-qlm-MRField.conf,https://bbva.ghe.com/platform/gl-cs-360-gdh-ql...,t_b0hn_toolkit_esg_general_data,NaN,b0hn-gl-hmm-qlt-toolkitesggeneraldamrfield-01....,"""19.0.0"""
6,t_b0hn_toolkit_esg_rating-qlm-MRField.conf,https://bbva.ghe.com/platform/gl-cs-360-gdh-ql...,t_b0hn_toolkit_esg_rating,NaN,b0hn-gl-hmm-qlt-toolkitesgratingmrfield-01.json,"""19.0.0"""
7,t_b0hn_toolkit_esg_sector-qlm-MRField.conf,https://bbva.ghe.com/platform/gl-cs-360-gdh-ql...,t_b0hn_toolkit_esg_sector,NaN,b0hn-gl-hmm-qlt-toolkitesgsectormrfield-01.json,"""19.0.0"""
2,t_b0hn_toolkit_esg_strategy-qlm-MRField.conf,https://bbva.ghe.com/platform/gl-cs-360-gdh-ql...,t_b0hn_toolkit_esg_strategy,NaN,b0hn-gl-hmm-qlt-toolkitesgstrategymrfield-01.json,"""19.0.0"""
4,t_b0hn_toolkit_esg_top_5_geo-qlm-MRField.conf,https://bbva.ghe.com/platform/gl-cs-360-gdh-ql...,t_b0hn_toolkit_esg_top_5_geo,NaN,b0hn-gl-hmm-qlt-toolkitesgtop5geomrfield-01.json,"""19.0.0"""
0,t_g5m3_sust_mob_operations-qlm-MRField.conf,https://bbva.ghe.com/platform/gl-cs-360-gdh-ql...,t_g5m3_sust_mob_operations,NaN,g5m3-gl-hmm-qlt-sustmoboperationsmrfield-01.json,"""19.0.0"""
1,t_kcdg_graph_nodes-qlm-MRField.conf,https://bbva.ghe.com/platform/gl-cs-360-gdh-ql...,t_kcdg_graph_nodes,NaN,kcdg-gl-hmm-qlt-graphnodesmrfield-01.json,"""19.0.0"""

In [35]:
print("versión de subida de jobs:")
print("\n- todos:")
print(list(conf_url.version.sort_values().unique()))
print("\n- por UA:")
list((conf_url.job.str[:4]+': '+conf_url.version).unique())

versión de subida de jobs:

- todos:
['"16.0.1"', '"16.1.5"', '"18.3.3"', '"18.3.5"', '"18.3.6"', '"18.3.7"', '"18.4.0"', '"18.4.1"', '"18.4.4"', '"18.4.6"', '"18.4.7"', '"19.0.0"']

- por UA:

['b0hn: "19.0.0"',
 'cgj7: "18.3.7"',
 'cgj7: "18.4.0"',
 'cmov: "18.4.4"',
 'ctar: "18.3.3"',
 'dast: "16.1.5"',
 'dtau: "18.4.1"',
 'ejb6: "18.3.3"',
 'fzpd: "18.3.3"',
 'g5m3: "19.0.0"',
 'j7il: "18.4.6"',
 'katc: "18.4.4"',
 'kcdg: "19.0.0"',
 'kceg: "18.4.4"',
 'kcpg: "18.3.3"',
 'kctd: "18.4.4"',
 'kfcm: "18.4.0"',
 'kmig: "18.3.3"',
 'knfa: "18.3.3"',
 'kpan: "18.4.0"',
 'ksrr: "18.3.3"',
 'kstb: "18.3.5"',
 'kszg: "18.4.7"',
 'kusu: "18.3.3"',
 'kwth: "18.3.3"',
 'l9ct: "18.4.1"',
 'l9sv: "18.3.5"',
 'msx9: "18.3.6"',
 'nm7r: "18.3.3"',
 'nols: "18.3.6"',
 'p68x: "18.3.3"',
 'p6r1: "18.3.3"',
 'r4fu: "18.3.6"',
 're4m: "18.4.1"',
 'rzua: "18.3.3"',
 'scat: "16.0.1"',
 'tdi3: "18.3.3"',
 'tlhr: "18.3.3"',
 'yfvh: "18.3.6"']