# SDM Componentes
Automatización de obtención de datos de [SDM Componentes](https://docs.google.com/spreadsheets/d/1Dene2gQPNl7ZXIKaf4AYqKzeOahMJ2uA-Vity1eXPUo/edit?gid=1637837061#gid=1637837061).  
El resultado se guardará en `./sdm_componentes/SDM_Componentes_final.csv`.  

1) Descargar como csv desde https://docs.google.com/spreadsheets/d/1aLELrHoXPwm8CSY2a6DN6DRqoIkruHQO37JrQcaZFNM/edit?gid=855523154#gid=855523154 y guardar como `./sdm_componentes/sdm_ultimos_confs_tabla.csv`
2) Descargar como csv desde https://docs.google.com/spreadsheets/d/1aLELrHoXPwm8CSY2a6DN6DRqoIkruHQO37JrQcaZFNM/edit?gid=75156217#gid=75156217 y guardar como `./sdm_componentes/sdm_parametros_confs.csv`

Actualizamos con resultado (`./sdm_componentes/SDM_Componentes_final.csv`):  
https://docs.google.com/spreadsheets/d/1aLELrHoXPwm8CSY2a6DN6DRqoIkruHQO37JrQcaZFNM/edit?gid=1324569054#gid=1324569054

In [24]:
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings("ignore")
pd.set_option('display.max_columns', None)

Q_actual = ['2Q26'] # <----------------------- ATENTOS CON ESTO, QUE SINO DETECTA QUE NO HAY CAMBIOS

Lectura

In [25]:
repos = pd.read_csv('repos/repos.csv')

sdm_confs       = pd.read_csv('./sdm_componentes/sdm_ultimos_confs_tabla.csv',skiprows=5).dropna(subset='tabla')
sdm_confs       .drop(columns=sdm_confs.columns[sdm_confs.columns.str.startswith('Unnamed')],inplace=True)
sdm_version     = sdm_confs[["Q","version.1"]].dropna().rename(columns={"version.1":'version'})
sdm_confs       = sdm_confs.drop(columns='Q').merge(sdm_version,how='left',on='version')

sdm_fecha       = sdm_confs[["Fecha2text","Version2"]].dropna().rename(columns={"Version2":'version', "Fecha2text":'Fecha'})
sdm_fecha.Fecha = pd.to_datetime(sdm_fecha.Fecha, format= '%d/%m/%Y')
sdm_fecha       = sdm_fecha.sort_values('Fecha',ascending=False).drop_duplicates('version')
sdm_fecha       .Fecha = sdm_fecha.Fecha.dt.strftime('%d/%m/%Y')
sdm_confs       = sdm_confs.drop(columns='Fecha').merge(sdm_fecha,how='left',on='version')


sdm_params      = pd.read_csv('./sdm_componentes/sdm_parametros_confs.csv').dropna(subset='conf')
sdm_params      .drop(columns=sdm_params.columns[sdm_params.columns.str.startswith('Unnamed')],inplace=True)

sdm_unique_params = sdm_params[['unique parameters.1','params.1']].dropna(subset='unique parameters.1')

In [26]:
sdm_confs

,SCHEMA,job europa,job america,job url,tabla,conf,STATUS IMPLANTATION,version,uuaa,url conf,Variables Job,count param,periodicidad,Mixta,Comentarios,conf_bitbucket,version.1,conf.1,job url.1,version.2,Version2,Fecha2,Fecha2text,Q,Fecha
0,https://artifactory.globaldevtools.bbva.com/ui...,NaN,NaN,NaN,t_b0hn_agg_output_ems_hgl,B0HN_agg-output-ems-hgl_MRField.conf,DELIVERED,15.1.0,B0HN,https://bbva.ghe.com/platform/gl-cs-360-gdh-ql...,CUTOFF_DATE,NaN,Monthly,DQ Local,Holding,NaN,19.0.1,t_b0hn_toolkit_ems_metric_target-qlm-MRField.conf,https://bbva.ghe.com/platform/gl-cs-360-gdh-ql...,NaN,19.0.1,28/04/2026,28/04/2026,1Q21,06/11/2024
1,https://artifactory.globaldevtools.bbva.com/ui...,NaN,NaN,NaN,t_b0hn_agg_output_ems_hgl,B0HN_agg-output-ems-hgl_MRField.conf,DELIVERED,15.1.0,B0HN,https://bbva.ghe.com/platform/gl-cs-360-gdh-ql...,CUTOFF_DATE,NaN,Monthly,DQ Local,Holding,NaN,19.0.1,t_b0hn_toolkit_ems_metric_target-qlm-MRField.conf,https://bbva.ghe.com/platform/gl-cs-360-gdh-ql...,NaN,19.0.1,28/04/2026,28/04/2026,1Q22,06/11/2024
2,https://artifactory.globaldevtools.bbva.com/ui...,NaN,NaN,NaN,t_b0hn_agg_output_ems_hgl,B0HN_agg-output-ems-hgl_MRField.conf,DELIVERED,15.1.0,B0HN,https://bbva.ghe.com/platform/gl-cs-360-gdh-ql...,CUTOFF_DATE,NaN,Monthly,DQ Local,Holding,NaN,19.0.1,t_b0hn_toolkit_ems_metric_target-qlm-MRField.conf,https://bbva.ghe.com/platform/gl-cs-360-gdh-ql...,NaN,19.0.1,28/04/2026,28/04/2026,1Q23,06/11/2024
3,https://artifactory.globaldevtools.bbva.com/ui...,NaN,NaN,NaN,t_b0hn_agg_output_ems_hgl,B0HN_agg-output-ems-hgl_MRField.conf,DELIVERED,15.1.0,B0HN,https://bbva.ghe.com/platform/gl-cs-360-gdh-ql...,CUTOFF_DATE,NaN,Monthly,DQ Local,Holding,NaN,19.0.1,t_b0hn_toolkit_ems_metric_target-qlm-MRField.conf,https://bbva.ghe.com/platform/gl-cs-360-gdh-ql...,NaN,19.0.1,28/04/2026,28/04/2026,1Q24,06/11/2024
4,https://artifactory.globaldevtools.bbva.com/ui...,NaN,NaN,NaN,t_b0hn_agg_output_ems_hgl,B0HN_agg-output-ems-hgl_MRField.conf,DELIVERED,15.1.0,B0HN,https://bbva.ghe.com/platform/gl-cs-360-gdh-ql...,CUTOFF_DATE,NaN,Monthly,DQ Local,Holding,NaN,19.0.1,t_b0hn_toolkit_ems_metric_target-qlm-MRField.conf,https://bbva.ghe.com/platform/gl-cs-360-gdh-ql...,NaN,19.0.1,28/04/2026,28/04/2026,2Q21,06/11/2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7534,https://artifactory.globaldevtools.bbva.com/ui...,https://bitbucket.globaldevtools.bbva.com/bitb...,https://bitbucket.globaldevtools.bbva.com/bitb...,https://bitbucket.globaldevtools.bbva.com/bitb...,t_tlhr_complaints_claims,TLHR_complaints-claims_MRObject.conf,DELIVERED,18.4.5,TLHR,https://bbva.ghe.com/platform/gl-cs-360-gdh-ql...,"CUTOFF_DATE, FECHA_VOLUMETRIC, LOWER_BOUND, UP...",NaN,Daily,DQ Local,Local,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1Q26,11/03/2026
7535,https://artifactory.globaldevtools.bbva.com/ui...,https://bitbucket.globaldevtools.bbva.com/bitb...,https://bitbucket.globaldevtools.bbva.com/bitb...,https://bitbucket.globaldevtools.bbva.com/bitb...,t_yfvh_cards_calc_balances,YFVH_cards-calc-balances_MRField.conf,DELIVERED,18.3.6,YFVH,https://bbva.ghe.com/platform/gl-cs-360-gdh-ql...,CUTOFF_DATE,NaN,Daily,DQ Local,Local,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3Q21,26/11/2025
7536,https://artifactory.globaldevtools.bbva.com/ui...,https://bitbucket.globaldevtools.bbva.com/bitb...,https://bitbucket.globaldevtools.bbva.com/bitb...,https://bitbucket.globaldevtools.bbva.com/bitb...,t_yfvh_cards_calc_balances,YFVH_cards-calc-balances_MRField.conf,DELIVERED,18.3.6,YFVH,https://bbva.ghe.com/platform/gl-cs-360-gdh-ql...,CUTOFF_DATE,NaN,Daily,DQ Local,Local,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4Q21,26/11/2025
7537,https://artifactory.globaldevtools.bbva.com/ui...,https://bitbucket.globaldevtools.bbva.com/bitb...,https://bitbucket.globaldevtools.bbva.com/bitb...,https://bitbucket.globaldevtools.bbva.com/bitb...,t_yfvh_cards_calc_balances,YFVH_cards-calc-balances_MRField.conf,DELIVERED,18.3.6,YFVH,https://bbva.ghe.com/platform/gl-cs-360-gdh-ql...,CUTOFF_DATE,NaN,Daily,DQ Local,Local,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4Q22,26/11/2025
7538,https://artifactory.globaldevtools.bbva.com/ui...,https://bitbucket.globaldevtools.bbva.com/bitb...,https://bitbucket.globaldevtools.bbva.com/bitb...,https://bitbucket.globaldevtools.bbva.com/bitb...,t_yfvh_cards_calc_balances,YFVH_cards-calc-balances_MRField.conf,DELIVERED,18.3.6,YFVH,https://bbva.ghe.com/platform/gl-cs-360-gdh-ql...,CUTOFF_DATE,NaN,Daily,DQ Local,Local,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4Q25,26/11/2025

In [27]:
conf_q = sdm_confs.groupby(['conf','Q']).count()['tabla'].reset_index().pivot(index='conf', columns='Q', values='tabla').fillna(0)>=1
Q_no_actual = conf_q.columns.values.tolist()
Q_no_actual.remove(Q_actual[0])
conf_q['Tipo'] = np.where(conf_q[Q_actual[0]] == False,'Sin cambios', 
                          np.where( (conf_q[Q_no_actual].any(axis=1) == True), 'Modificado', 'Nuevo'))
conf_q = conf_q['Tipo']
conf_q = conf_q.reset_index()
sdm_confs = sdm_confs.merge(conf_q, on='conf', how='left')

## Transformación

### 1) Params

In [28]:
#rellenar en origen cuando falten!!!!
sdm_params_clean        = sdm_params[sdm_params["STATUS IMPLANTATION"] == "DELIVERED"]
sdm_params_clean        = sdm_params_clean[['conf','unique parameters','params']].drop_duplicates(subset=['conf','params'])
sdm_params_clean.params = sdm_params_clean.params.str.replace('^,\ ','',regex=True)
sdm_params_clean        = sdm_params_clean.sort_values('params',ascending=True)
print('---------------\n- Null params -\n---------------\n ¡REVISAR! (Rellenar cuando falten en origen):\n----------------------------------------------')
print('https://docs.google.com/spreadsheets/d/1VlE-2bK8370eYNGi5kEeXWonZ_emMrw8VAS-fNiwol8/edit?gid=1150342608#gid=1150342608&range=K:L')
sdm_params_clean[sdm_params_clean.params.isnull()]
########################################################

---------------
- Null params -
---------------
 ¡REVISAR! (Rellenar cuando falten en origen):
----------------------------------------------
https://docs.google.com/spreadsheets/d/1VlE-2bK8370eYNGi5kEeXWonZ_emMrw8VAS-fNiwol8/edit?gid=1150342608#gid=1150342608&range=K:L

Empty DataFrame
Columns: [conf, unique parameters, params]
Index: []

In [29]:
# sdm_params_clean.params.str.split()
sdm_params_clean_split = (sdm_params_clean.set_index('conf')
            ['params'].str.split(',\s*', expand=True)
            .stack()
            .reset_index(name='param')
            .drop(columns='level_1')
            )
sdm_params_clean_split.param.unique()

array(['CATALOG_COLUMN_0', 'CATALOG_CODE_0', 'CATALOG_TABLE_0', 'SOURCE',
       'CATALOG_COLUMN_1', 'CATALOG_CODE_1', 'CATALOG_TABLE_1',
       'extralibs', 'CATALOG_COLUMN_10', 'CATALOG_CODE_10',
       'CATALOG_TABLE_10', 'CATALOG_COLUMN_11', 'CATALOG_CODE_11',
       'CATALOG_TABLE_11', 'CATALOG_COLUMN_2', 'CATALOG_CODE_2',
       'CATALOG_TABLE_2', 'CATALOG_COLUMN_3', 'CATALOG_CODE_3',
       'CATALOG_TABLE_3', 'CATALOG_COLUMN_4', 'CATALOG_CODE_4',
       'CATALOG_TABLE_4', 'CATALOG_COLUMN_5', 'CATALOG_CODE_5',
       'CATALOG_TABLE_5', 'CATALOG_COLUMN_6', 'CATALOG_CODE_6',
       'CATALOG_TABLE_6', 'CATALOG_COLUMN_7', 'CATALOG_CODE_7',
       'CATALOG_TABLE_7', 'CATALOG_COLUMN_8', 'CATALOG_CODE_8',
       'CATALOG_TABLE_8', 'CATALOG_COLUMN_9', 'CATALOG_CODE_9',
       'CATALOG_TABLE_9', 'CLOSING_DATE', 'ADOBE_REPORT_SUITE_NAME',
       'DATE_VOLUMETRIC', 'LOWER_BOUND', 'UPPER_BOUND',
       'FECHA_VOLUMETRIC', 'CUTOFF_DATE', 'ENTIFIC_ID', 'IS_VOL_CRITICAL',
       'SOURCE_LIST', 'OPERATION_DATE', 'PREVIOUS_CUTOFF_DATE'],
      dtype=object)

In [30]:
sdm_params_clean_params = sdm_params_clean_split.groupby('conf')['param'].agg(params_clean= lambda x: ', '.join(sorted(list(set(x))))).reset_index()
# print(sdm_params_clean_params.params_clean.unique())
sdm_params_clean_params

,conf,params_clean
0,B0HN_agg-output-ems-hgl_KSAG_holding-business-...,CUTOFF_DATE
1,B0HN_agg-output-ems-hgl_MRField.conf,CUTOFF_DATE
2,B0HN_agg-output-ems-hgl_MRObject.conf,"CUTOFF_DATE, FECHA_VOLUMETRIC, LOWER_BOUND, UP..."
3,B0HN_sust-group-mark_KSAG_holding-business-gro...,"CUTOFF_DATE, SOURCE_LIST"
4,B0HN_sust-group-mark_MRField.conf,"CUTOFF_DATE, SOURCE_LIST"
...,...,...
835,t_b0hn_toolkit_esg_sector-qlm-MRField.conf,CUTOFF_DATE
836,t_b0hn_toolkit_esg_strategy-qlm-MRField.conf,CUTOFF_DATE
837,t_b0hn_toolkit_esg_top_5_geo-qlm-MRField.conf,CUTOFF_DATE
838,t_g5m3_sust_mob_operations-qlm-MRField.conf,CUTOFF_DATE
839,t_kcdg_graph_nodes-qlm-MRField.conf,CUTOFF_DATE

### 2) SDM Confs

In [31]:
dict_conf_type = {
    "MRField":  "1",
    "MRObject": "2",
    "MMRule":   "3"
}
dict_periodicidad = {
    'Daily':    'Diaria',
    'Monthly':  'Mensual',
    'Annually': 'Anual',
    'Punctual': 'Puntual',
    'Weekly':   'Semanal'
}

sdm_confs                               = sdm_confs[sdm_confs["STATUS IMPLANTATION"] == "DELIVERED"]
sdm_confs                               = sdm_confs.merge(sdm_params_clean_params, how='left', on='conf')
sdm_confs['Version_ord']                = pd.to_numeric(sdm_confs.version.str.replace('.','',regex=False))
sdm_confs                               .sort_values('Version_ord',ascending=False,inplace=True)
sdm_confs                               .drop_duplicates(subset='conf',keep='first',inplace=True)

# sdm_confs['conf_type']                  = sdm_confs.conf.str.extract('((_MR|_MM).*\.conf)')[0].str.replace('_','').str.replace('.conf','')
sdm_confs['conf_type']                  = sdm_confs.conf.str.extract('((-MR|-MM).*\.conf)')[0].str.replace('-','').str.replace('.conf','')
sdm_confs['conf_ord']                   = sdm_confs['conf_type'] .replace(dict_conf_type)
sdm_confs                               .sort_values(by=['tabla','conf_type'],inplace=True)
sdm_confs['Fecha / Release']            = sdm_confs["Fecha"]
sdm_confs['Tipo']                       = sdm_confs['Tipo']
sdm_confs['UUAA']                       = sdm_confs.tabla.str[:6].str[2:].str.upper()
sdm_confs['Proceso / Tabla Master']     = sdm_confs.tabla
sdm_confs['Tabla']                      = sdm_confs.tabla
sdm_confs['Versión']                    = 'latest'
sdm_confs['Etapa / Fase']               = 'Master'
sdm_confs['Tipo Componente']            = "Hammurabi"
sdm_confs['Subtipo Componente']         = sdm_confs['conf_type']
sdm_confs['Versión SW']                 = '"' + sdm_confs.version.astype(str) + '"'

sdm_confs['job'] = sdm_confs['job europa'].str.split('europa/').str[1].str.split('.json?').str[0]
sdm_confs['job_europa_hiper']           = "=HYPERLINK(\"" + sdm_confs['job europa'] + "\";\"" + sdm_confs['job'] + "\")"
sdm_confs['job_america_ada_hiper']      = "=HYPERLINK(\"" + sdm_confs['job america'].str.replace('/america/','/america-ada/') + "\";\"" + sdm_confs['job'] + "\")"
sdm_confs['job_america_hiper']          = "=HYPERLINK(\"" + sdm_confs['job america'] + "\";\"" + sdm_confs['job'] + "\")"
sdm_confs['Job ADA Europa (Bitbucket)']     = sdm_confs['job_europa_hiper']
sdm_confs['Job ADA América (Bitbucket)']    = sdm_confs['job_america_ada_hiper']
sdm_confs['Job Datio América (Bitbucket)']  = sdm_confs['job_america_hiper']
sdm_confs['Conf (opcional)']            = "=HYPERLINK(\"" + sdm_confs['url conf'] + "\";\"" + sdm_confs['conf'] + "\")" 
sdm_confs['Variables Job']              = sdm_confs['params_clean']
sdm_confs['Ejemplo (opcional)']         = ' '
sdm_confs['ID Orden']                   = ' '
sdm_confs['Periodicidad']               = sdm_confs['periodicidad'].str.strip().replace(dict_periodicidad)
sdm_confs['Mixta']                      = np.where(sdm_confs['Comentarios'] == 'Holding', 'Holding to Local', sdm_confs['Mixta'])
sdm_confs['Comentarios']                = sdm_confs.Comentarios
sdm_confs['ESP']                        = np.where(sdm_confs['Comentarios'] == 'Holding', False, True)
sdm_confs['MEX']                        = np.where(sdm_confs['Comentarios'] == 'Holding', False, True)
sdm_confs['PER']                        = np.where(sdm_confs['Comentarios'] == 'Holding', False, True)
sdm_confs['COL']                        = np.where(sdm_confs['Comentarios'] == 'Holding', False, True)
sdm_confs['ARG']                        = np.where(sdm_confs['Comentarios'] == 'Holding', False, True)

sdm_confs = sdm_confs.merge(repos,how='left',on='UUAA')
print("proyectos nulos:", sdm_confs.project.isnull().sum())
if sdm_confs.project.isnull().sum() > 0:
    raise print("revisar proyectos en repos/repos.csv")
#seguimos apuntando a Bitbucket
#sdm_confs['Conf (opcional)']            = 'https://bitbucket.globaldevtools.bbva.com/bitbucket/projects/' + sdm_confs['project'] + '/repos/glgldh360gloqlt/browse/hammurabi/confs/master/' + sdm_confs['UUAA'].str.lower() + '/' + sdm_confs['conf']
sdm_confs.head()

proyectos nulos: 0

,SCHEMA,job europa,job america,job url,tabla,conf,STATUS IMPLANTATION,version,uuaa,url conf,Variables Job,count param,periodicidad,Mixta,Comentarios,conf_bitbucket,version.1,conf.1,job url.1,version.2,Version2,Fecha2,Fecha2text,Q,Fecha,Tipo,params_clean,Version_ord,conf_type,conf_ord,Fecha / Release,UUAA,Proceso / Tabla Master,Tabla,Versión,Etapa / Fase,Tipo Componente,Subtipo Componente,Versión SW,job,job_europa_hiper,job_america_ada_hiper,job_america_hiper,Job ADA Europa (Bitbucket),Job ADA América (Bitbucket),Job Datio América (Bitbucket),Conf (opcional),Ejemplo (opcional),ID Orden,Periodicidad,ESP,MEX,PER,COL,ARG,project
0,https://artifactory.globaldevtools.bbva.com/ui...,NaN,NaN,NaN,t_b0hn_agg_output_ems_hgl,B0HN_agg-output-ems-hgl_MRField.conf,DELIVERED,18.3.3,B0HN,https://bbva.ghe.com/platform/gl-cs-360-gdh-ql...,CUTOFF_DATE,NaN,Monthly,Holding to Local,Holding,NaN,19.0.0,t_b0hn_toolkit_esg_sector-qlm-MRField.conf,https://bbva.ghe.com/platform/gl-cs-360-gdh-ql...,NaN,18.4.6,46099,18/03/2026,2Q24,04/11/2025,Sin cambios,CUTOFF_DATE,1833,NaN,NaN,04/11/2025,B0HN,t_b0hn_agg_output_ems_hgl,t_b0hn_agg_output_ems_hgl,latest,Master,Hammurabi,NaN,"""18.3.3""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,"=HYPERLINK(""https://bbva.ghe.com/platform/gl-c...",,,Mensual,False,False,False,False,False,GL_B0HN_APP-ID-23103_DSG
1,https://artifactory.globaldevtools.bbva.com/ui...,NaN,NaN,NaN,t_b0hn_agg_output_ems_hgl,B0HN_agg-output-ems-hgl_KSAG_holding-business-...,DELIVERED,18.3.0,B0HN,https://bbva.ghe.com/platform/gl-cs-360-gdh-ql...,CUTOFF_DATE,NaN,Monthly,Holding to Local,Holding,NaN,19.0.0,t_b0hn_toolkit_esg_rating-qlm-MRField.conf,https://bbva.ghe.com/platform/gl-cs-360-gdh-ql...,NaN,18.4.7,46119,7/04/2026,4Q25,08/10/2025,Sin cambios,CUTOFF_DATE,1830,NaN,NaN,08/10/2025,B0HN,t_b0hn_agg_output_ems_hgl,t_b0hn_agg_output_ems_hgl,latest,Master,Hammurabi,NaN,"""18.3.0""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,"=HYPERLINK(""https://bbva.ghe.com/platform/gl-c...",,,Mensual,False,False,False,False,False,GL_B0HN_APP-ID-23103_DSG
2,https://artifactory.globaldevtools.bbva.com/ui...,NaN,NaN,NaN,t_b0hn_agg_output_ems_hgl,B0HN_agg-output-ems-hgl_MRObject.conf,DELIVERED,15.1.0,B0HN,https://bbva.ghe.com/platform/gl-cs-360-gdh-ql...,"CUTOFF_DATE, FECHA_VOLUMETRIC, LOWER_BOUND, UP...",NaN,Monthly,Holding to Local,Holding,NaN,19.0.0,t_b0hn_toolkit_esg_general_data-qlm-MRField.conf,https://bbva.ghe.com/platform/gl-cs-360-gdh-ql...,NaN,19.0.0,46133,21/04/2026,4Q23,06/11/2024,Sin cambios,"CUTOFF_DATE, FECHA_VOLUMETRIC, LOWER_BOUND, UP...",1510,NaN,NaN,06/11/2024,B0HN,t_b0hn_agg_output_ems_hgl,t_b0hn_agg_output_ems_hgl,latest,Master,Hammurabi,NaN,"""15.1.0""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,"=HYPERLINK(""https://bbva.ghe.com/platform/gl-c...",,,Mensual,False,False,False,False,False,GL_B0HN_APP-ID-23103_DSG
3,https://artifactory.globaldevtools.bbva.com/ui...,NaN,NaN,NaN,t_b0hn_sust_group_mark,B0HN_sust-group-mark_MRField.conf,DELIVERED,18.3.3,B0HN,https://bbva.ghe.com/platform/gl-cs-360-gdh-ql...,"CUTOFF_DATE, SOURCE_LIST",NaN,Monthly,DQ Local,Both,NaN,19.0.0,t_b0hn_toolkit_esg_strategy-qlm-MRField.conf,https://bbva.ghe.com/platform/gl-cs-360-gdh-ql...,NaN,18.4.5,46092,11/03/2026,4Q25,04/11/2025,Sin cambios,"CUTOFF_DATE, SOURCE_LIST",1833,NaN,NaN,04/11/2025,B0HN,t_b0hn_sust_group_mark,t_b0hn_sust_group_mark,latest,Master,Hammurabi,NaN,"""18.3.3""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,"=HYPERLINK(""https://bbva.ghe.com/platform/gl-c...",,,Mensual,True,True,True,True,True,GL_B0HN_APP-ID-23103_DSG
4,https://artifactory.globaldevtools.bbva.com/ui...,NaN,NaN,NaN,t_b0hn_sust_group_mark,B0HN_sust-group-mark_MRObject.conf,DELIVERED,18.3.3,B0HN,https://bbva.ghe.com/platform/gl-cs-360-gdh-ql...,"CUTOFF_DATE, FECHA_VOLUMETRIC, LOWER_BOUND, SO...",NaN,Monthly,DQ Local,Both,NaN,19.0.0,CGJ7_customer-carbon-footprint_MRField.conf,https://bitbucket.globaldevtools.bbva.com/bitb...,NaN,18.4.3,46071,18/02/2026,4Q25,04/11/2025,Sin cambios,"CUTOFF_DATE, FECHA_VOLUMETRIC, LOWER_BOUND, SO...",1833,NaN,NaN,04/11/2025,B0HN,t_b0hn_sust_group_mark,t_b0hn_sust_group_mark,latest,Master,Hammurabi,NaN,"""18.3.3""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,"=HYPERLINK(""https://bbva.ghe.com/platform/gl-c...",,,Mensual,True,True,True,True,True,GL_B0HN_APP-ID-23103_DSG

### 3) SDM Componentes - Final

In [32]:
sdm_componentes         = sdm_confs[[
    'Fecha / Release','Tipo','UUAA','Proceso / Tabla Master','Tabla','Versión','Etapa / Fase','Tipo Componente','Subtipo Componente','Versión SW',
    'Job ADA Europa (Bitbucket)','Job ADA América (Bitbucket)','Job Datio América (Bitbucket)','Conf (opcional)','Variables Job','Ejemplo (opcional)', 'ID Orden', 'Periodicidad', 'Mixta', 'Comentarios','ESP', 'MEX', 'PER', 'COL', 'ARG'
    ]]

sdm_componentes         .Periodicidad.fillna('Diaria',inplace=True)
print('NULOS:')
print(sdm_componentes.isnull().sum())
sdm_componentes['type'] = sdm_componentes['Conf (opcional)'].str.extract(r'_(.{6,8}).conf').replace({'MRField':1, 'MRObject':2, 'MMRule':3})
sdm_componentes         .sort_values(['Tabla','type'], inplace=True)
sdm_componentes         .drop(columns='type', inplace=True)
sdm_componentes         .to_csv('./sdm_componentes/SDM_Componentes_final.csv',sep=';',index=False)
sdm_componentes         .tail(2)

NULOS:
Fecha / Release                    0
Tipo                               0
UUAA                               0
Proceso / Tabla Master             0
Tabla                              0
Versión                            0
Etapa / Fase                       0
Tipo Componente                    0
Subtipo Componente               832
Versión SW                         0
Job ADA Europa (Bitbucket)        39
Job ADA América (Bitbucket)       39
Job Datio América (Bitbucket)     39
Conf (opcional)                    0
Variables Job                      0
Ejemplo (opcional)                 0
ID Orden                           0
Periodicidad                       0
Mixta                              0
Comentarios                        9
ESP                                0
MEX                                0
PER                                0
COL                                0
ARG                                0
dtype: int64

,Fecha / Release,Tipo,UUAA,Proceso / Tabla Master,Tabla,Versión,Etapa / Fase,Tipo Componente,Subtipo Componente,Versión SW,Job ADA Europa (Bitbucket),Job ADA América (Bitbucket),Job Datio América (Bitbucket),Conf (opcional),Variables Job,Ejemplo (opcional),ID Orden,Periodicidad,Mixta,Comentarios,ESP,MEX,PER,COL,ARG
837,11/03/2026,Sin cambios,TLHR,t_tlhr_complaints_claims,t_tlhr_complaints_claims,latest,Master,Hammurabi,NaN,"""18.4.5""","=HYPERLINK(""https://bitbucket.globaldevtools.b...","=HYPERLINK(""https://bitbucket.globaldevtools.b...","=HYPERLINK(""https://bitbucket.globaldevtools.b...","=HYPERLINK(""https://bbva.ghe.com/platform/gl-c...","CUTOFF_DATE, FECHA_VOLUMETRIC, LOWER_BOUND, UP...",,,Diaria,DQ Local,Local,True,True,True,True,True
839,26/11/2025,Sin cambios,YFVH,t_yfvh_cards_calc_balances,t_yfvh_cards_calc_balances,latest,Master,Hammurabi,NaN,"""18.3.6""","=HYPERLINK(""https://bitbucket.globaldevtools.b...","=HYPERLINK(""https://bitbucket.globaldevtools.b...","=HYPERLINK(""https://bitbucket.globaldevtools.b...","=HYPERLINK(""https://bbva.ghe.com/platform/gl-c...",CUTOFF_DATE,,,Diaria,DQ Local,Local,True,True,True,True,True

In [33]:
# NO DEBERÍA HABER NULOS en casos que no sean Holding !!!!!!!!!!!
# -> (revisar ultimos confs tabla o wip_conf_url_NEW sin subir)

sdm_componentes[(sdm_componentes['Job ADA Europa (Bitbucket)'].isnull()) & (sdm_componentes['Comentarios']!='Holding')]

,Fecha / Release,Tipo,UUAA,Proceso / Tabla Master,Tabla,Versión,Etapa / Fase,Tipo Componente,Subtipo Componente,Versión SW,Job ADA Europa (Bitbucket),Job ADA América (Bitbucket),Job Datio América (Bitbucket),Conf (opcional),Variables Job,Ejemplo (opcional),ID Orden,Periodicidad,Mixta,Comentarios,ESP,MEX,PER,COL,ARG
3,04/11/2025,Sin cambios,B0HN,t_b0hn_sust_group_mark,t_b0hn_sust_group_mark,latest,Master,Hammurabi,NaN,"""18.3.3""",NaN,NaN,NaN,"=HYPERLINK(""https://bbva.ghe.com/platform/gl-c...","CUTOFF_DATE, SOURCE_LIST",,,Mensual,DQ Local,Both,True,True,True,True,True
4,04/11/2025,Sin cambios,B0HN,t_b0hn_sust_group_mark,t_b0hn_sust_group_mark,latest,Master,Hammurabi,NaN,"""18.3.3""",NaN,NaN,NaN,"=HYPERLINK(""https://bbva.ghe.com/platform/gl-c...","CUTOFF_DATE, FECHA_VOLUMETRIC, LOWER_BOUND, SO...",,,Mensual,DQ Local,Both,True,True,True,True,True
5,04/11/2025,Sin cambios,B0HN,t_b0hn_sust_group_mark,t_b0hn_sust_group_mark,latest,Master,Hammurabi,NaN,"""18.3.3""",NaN,NaN,NaN,"=HYPERLINK(""https://bbva.ghe.com/platform/gl-c...","CUTOFF_DATE, SOURCE_LIST",,,Mensual,DQ Local,Both,True,True,True,True,True
75,11/03/2026,Sin cambios,G5M3,t_g5m3_agg_mlzed_amount,t_g5m3_agg_mlzed_amount,latest,Master,Hammurabi,NaN,"""18.4.5""",NaN,NaN,NaN,"=HYPERLINK(""https://bbva.ghe.com/platform/gl-c...","CUTOFF_DATE, ENTIFIC_ID",,,Mensual,DQ Local,Both,True,True,True,True,True
76,26/02/2026,Sin cambios,G5M3,t_g5m3_agg_mlzed_amount,t_g5m3_agg_mlzed_amount,latest,Master,Hammurabi,NaN,"""18.4.4""",NaN,NaN,NaN,"=HYPERLINK(""https://bbva.ghe.com/platform/gl-c...","CUTOFF_DATE, ENTIFIC_ID",,,Mensual,DQ Local,Both,True,True,True,True,True
78,04/11/2025,Sin cambios,G5M3,t_g5m3_movement_carbon_footprint,t_g5m3_movement_carbon_footprint,latest,Master,Hammurabi,NaN,"""18.3.3""",NaN,NaN,NaN,"=HYPERLINK(""https://bbva.ghe.com/platform/gl-c...","CUTOFF_DATE, OPERATION_DATE, PREVIOUS_CUTOFF_DATE",,,Diaria,DQ Local,Local,True,True,True,True,True
82,06/11/2024,Sin cambios,G5M3,t_g5m3_movement_carbon_footprint,t_g5m3_movement_carbon_footprint,latest,Master,Hammurabi,NaN,"""15.1.0""",NaN,NaN,NaN,"=HYPERLINK(""https://bbva.ghe.com/platform/gl-c...","CUTOFF_DATE, FECHA_VOLUMETRIC, LOWER_BOUND, UP...",,,Diaria,DQ Local,Local,True,True,True,True,True
79,08/10/2025,Sin cambios,G5M3,t_g5m3_movement_carbon_footprint,t_g5m3_movement_carbon_footprint,latest,Master,Hammurabi,NaN,"""18.3.0""",NaN,NaN,NaN,"=HYPERLINK(""https://bbva.ghe.com/platform/gl-c...","CUTOFF_DATE, OPERATION_DATE",,,Diaria,DQ Local,Local,True,True,True,True,True
80,08/10/2025,Sin cambios,G5M3,t_g5m3_movement_carbon_footprint,t_g5m3_movement_carbon_footprint,latest,Master,Hammurabi,NaN,"""18.3.0""",NaN,NaN,NaN,"=HYPERLINK(""https://bbva.ghe.com/platform/gl-c...","CUTOFF_DATE, OPERATION_DATE",,,Diaria,DQ Local,Local,True,True,True,True,True
81,08/10/2025,Sin cambios,G5M3,t_g5m3_movement_carbon_footprint,t_g5m3_movement_carbon_footprint,latest,Master,Hammurabi,NaN,"""18.3.0""",NaN,NaN,NaN,"=HYPERLINK(""https://bbva.ghe.com/platform/gl-c...","CUTOFF_DATE, OPERATION_DATE",,,Diaria,DQ Local,Local,True,True,True,True,True
86,06/11/2024,Sin cambios,G5M3,t_g5m3_sust_mob_operations,t_g5m3_sust_mob_operations,latest,Master,Hammurabi,NaN,"""15.1.0""",NaN,NaN,NaN,"=HYPERLINK(""https://bbva.ghe.com/platform/gl-c...","CUTOFF_DATE, FECHA_VOLUMETRIC, LOWER_BOUND, UP...",,,Diaria,DQ Local,Local,True,True,True,True,True
84,14/10/2025,Sin cambios,G5M3,t_g5m3_sust_mob_operations,t_g5m3_sust_mob_operations,latest,Master,Hammurabi,NaN,"""18.3.1""",NaN,NaN,NaN,"=HYPERLINK(""https://bbva.ghe.com/platform/gl-c...",CUTOFF_DATE,,,Diaria,DQ Local,Local,True,True,True,True,True
85,08/10/2025,Sin cambios,G5M3,t_g5m3_sust_mob_operations,t_g5m3_sust_mob_operations,latest,Master,Hammurabi,NaN,"""18.3.0""",NaN,NaN,NaN,"=HYPERLINK(""https://bbva.ghe.com/platform/gl-c...",CUTOFF_DATE,,,Diaria,DQ Local,Local,True,True,True,True,True
91,05/02/2026,Sin cambios,G5M3,t_g5m3_sust_mob_operations_eod,t_g5m3_sust_mob_operations_eod,latest,Master,Hammurabi,NaN,"""18.4.2""",NaN,NaN,NaN,"=HYPERLINK(""https://bbva.ghe.com/platform/gl-c...",CUTOFF_DATE,,,Diaria,DQ Local,Local,True,True,True,True,True
93,06/11/2024,Sin cambios,G5M3,t_g5m3_sust_mob_operations_eod,t_g5m3_sust_mob_operations_eod,latest,Master,Hammurabi,NaN,"""15.1.0""",NaN,NaN,NaN,"=HYPERLINK(""https://bbva.ghe.com/platform/gl-c...","CUTOFF_DATE, FECHA_VOLUMETRIC, LOWER_BOUND, UP...",,,Diaria,DQ Local,Local,True,True,True,True,True
92,22/09/2025,Sin cambios,G5M3,t_g5m3_sust_mob_operations_eod,t_g5m3_sust_mob_operations_eod,latest,Master,Hammurabi,NaN,"""18.1.1""",NaN,NaN,NaN,"=HYPERLINK(""https://bbva.ghe.com/platform/gl-c...",CUTOFF_DATE,,,Diaria,DQ Local,Local,True,True,True,True,True
155,29/08/2025,Sin cambios,KCDG,t_kcdg_graph_edges,t_kcdg_graph_edges,latest,Master,Hammurabi,NaN,"""17.6.0""",NaN,NaN,NaN,"=HYPERLINK(""https://bbva.ghe.com/platform/gl-c...",CUTOFF_DATE,,,Mensual,DQ Local,Local,True,True,True,True,True
154,02/10/2025,Sin cambios,KCDG,t_kcdg_graph_edges,t_kcdg_graph_edges,latest,Master,Hammurabi,NaN,"""18.2.0""",NaN,NaN,NaN,"=HYPERLINK(""https://bbva.ghe.com/platform/gl-c...","CUTOFF_DATE, FECHA_VOLUMETRIC, LOWER_BOUND, UP...",,,Mensual,DQ Local,Local,True,True,True,True,True
153,08/10/2025,Sin cambios,KCDG,t_kcdg_graph_edges,t_kcdg_graph_edges,latest,Master,Hammurabi,NaN,"""18.3.0""",NaN,NaN,NaN,"=HYPERLINK(""https://bbva.ghe.com/platform/gl-c...",CUTOFF_DATE,,,Mensual,DQ Local,Local,True,True,True,True,True
157,02/10/2025,Sin cambios,KCDG,t_kcdg_graph_nodes,t_kcdg_graph_nodes,latest,Master,Hammurabi,NaN,"""18.2.0""",NaN,NaN,NaN,"=HYPERLINK(""https://bbva.ghe.com/platform/gl-c...","CUTOFF_DATE, FECHA_VOLUMETRIC, LOWER_BOUND, UP...",,,Mensual,DQ Local,Local,True,True,True,True,True
200,11/03/2026,Sin cambios,KCEG,t_kceg_customer_products,t_kceg_customer_products,latest,Master,Hammurabi,NaN,"""18.4.5""",NaN,NaN,NaN,"=HYPERLINK(""https://bbva.ghe.com/platform/gl-c...",CUTOFF_DATE,,,Mensual,DQ Local,Local,True,True,True,True,True

**Filtramos X tablas por orden**

In [34]:
tablas=[
    't_kctd_interaction_hit_quality',
    't_kceg_customer_engagement'
]
sdm_componentes_filtrado        = sdm_componentes[sdm_componentes.Tabla.isin(tablas)]
sdm_componentes_filtrado.Tabla  = sdm_componentes_filtrado.Tabla.astype("category").cat.set_categories(tablas)
sdm_componentes_filtrado        = sdm_componentes_filtrado.sort_values('Tabla')
sdm_componentes_filtrado        .to_csv('./sdm_componentes/filtrado/SDM_Componentes_final_FILTRADO.csv',sep=';',index=False)
sdm_componentes_filtrado

,Fecha / Release,Tipo,UUAA,Proceso / Tabla Master,Tabla,Versión,Etapa / Fase,Tipo Componente,Subtipo Componente,Versión SW,Job ADA Europa (Bitbucket),Job ADA América (Bitbucket),Job Datio América (Bitbucket),Conf (opcional),Variables Job,Ejemplo (opcional),ID Orden,Periodicidad,Mixta,Comentarios,ESP,MEX,PER,COL,ARG
356,06/11/2024,Sin cambios,KCTD,t_kctd_interaction_hit_quality,t_kctd_interaction_hit_quality,latest,Master,Hammurabi,NaN,"""15.1.0""","=HYPERLINK(""https://bitbucket.globaldevtools.b...","=HYPERLINK(""https://bitbucket.globaldevtools.b...","=HYPERLINK(""https://bitbucket.globaldevtools.b...","=HYPERLINK(""https://bbva.ghe.com/platform/gl-c...","ADOBE_REPORT_SUITE_NAME, CLOSING_DATE",,,Diaria,DQ Local,Both,True,True,True,True,True
357,06/11/2024,Sin cambios,KCTD,t_kctd_interaction_hit_quality,t_kctd_interaction_hit_quality,latest,Master,Hammurabi,NaN,"""15.1.0""","=HYPERLINK(""https://bitbucket.globaldevtools.b...","=HYPERLINK(""https://bitbucket.globaldevtools.b...","=HYPERLINK(""https://bitbucket.globaldevtools.b...","=HYPERLINK(""https://bbva.ghe.com/platform/gl-c...","ADOBE_REPORT_SUITE_NAME, CLOSING_DATE, DATE_VO...",,,Diaria,DQ Local,Both,True,True,True,True,True
195,04/11/2025,Sin cambios,KCEG,t_kceg_customer_engagement,t_kceg_customer_engagement,latest,Master,Hammurabi,NaN,"""18.3.3""","=HYPERLINK(""https://bitbucket.globaldevtools.b...","=HYPERLINK(""https://bitbucket.globaldevtools.b...","=HYPERLINK(""https://bitbucket.globaldevtools.b...","=HYPERLINK(""https://bbva.ghe.com/platform/gl-c...","CUTOFF_DATE, PREVIOUS_CUTOFF_DATE",,,Mensual,DQ Local,Local,True,True,True,True,True
197,06/11/2024,Sin cambios,KCEG,t_kceg_customer_engagement,t_kceg_customer_engagement,latest,Master,Hammurabi,NaN,"""15.1.0""","=HYPERLINK(""https://bitbucket.globaldevtools.b...","=HYPERLINK(""https://bitbucket.globaldevtools.b...","=HYPERLINK(""https://bitbucket.globaldevtools.b...","=HYPERLINK(""https://bbva.ghe.com/platform/gl-c...","CUTOFF_DATE, FECHA_VOLUMETRIC, LOWER_BOUND, UP...",,,Mensual,DQ Local,Local,True,True,True,True,True
196,23/10/2025,Sin cambios,KCEG,t_kceg_customer_engagement,t_kceg_customer_engagement,latest,Master,Hammurabi,NaN,"""18.3.2""","=HYPERLINK(""https://bitbucket.globaldevtools.b...","=HYPERLINK(""https://bitbucket.globaldevtools.b...","=HYPERLINK(""https://bitbucket.globaldevtools.b...","=HYPERLINK(""https://bbva.ghe.com/platform/gl-c...",CUTOFF_DATE,,,Mensual,DQ Local,Local,True,True,True,True,True

In [35]:
sdm_componentes['Variables Job'].value_counts()

Variables Job
CUTOFF_DATE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              528
CUTOFF_DATE, FECHA_VOLUMETRIC, LOWER_BOUND, UPPER_BOUND                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  149
CUTOFF_DATE, SOURCE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       31
CUTOFF_DATE, FECHA_VOLUMETRIC, IS_VOL_CRITICAL, LOWER_BOUND, UPPER_BOUND                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  25
CATALOG_CODE_0, CATALOG_COLUMN_0, CATALOG_TABLE_0, CUTOFF_DATE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            24
CUTOFF_DATE, FECHA_VOLUMETRIC, LOWER_BOUND, SOURCE, UPPER_BOUND                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           12
CUTOFF_DATE, SOURCE_LIST                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   7
CUTOFF_DATE, extralibs                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     7
CATALOG_CODE_0, CATALOG_CODE_1, CATALOG_COLUMN_0, CATALOG_COLUMN_1, CATALOG_TABLE_0, CATALOG_TABLE_1, CUTOFF_DATE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          6
ADOBE_REPORT_SUITE_NAME, CLOSING_DATE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      5
CATALOG_CODE_0, CATALOG_CODE_1, CATALOG_CODE_2, CATALOG_COLUMN_0, CATALOG_COLUMN_1, CATALOG_COLUMN_2, CATALOG_TABLE_0, CATALOG_TABLE_1, CATALOG_TABLE_2, CUTOFF_DATE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       5
CUTOFF_DATE, FECHA_VOLUMETRIC, LOWER_BOUND, SOURCE_LIST, UPPER_BOUND                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       4
CUTOFF_DATE, PREVIOUS_CUTOFF_DATE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          4
CATALOG_CODE_1, CATALOG_CODE_2, CATALOG_CODE_3, CATALOG_CODE_4, CATALOG_CODE_5, CATALOG_CODE_6, CATALOG_COLUMN_1, CATALOG_COLUMN_2, CATALOG_COLUMN_3, CATALOG_COLUMN_4, CATALOG_COLUMN_5, CATALOG_COLUMN_6, CATALOG_TABLE_1, CATALOG_TABLE_2, CATALOG_TABLE_3, CATALOG_TABLE_4, CATALOG_TABLE_5, CATALOG_TABLE_6, CUTOFF_DATE                                                                                                                                                                                                                                                                                                                              3
CUTOFF_DATE, OPERATION_DATE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                3
CATALOG_CODE_0, CATALOG_CODE_1, CATALOG_CODE_2, CATALOG_CODE_3, CATALOG_CODE_4, CATALOG_CODE_5, CATALOG_COLUMN_0, CATALOG_COLUMN_1, CATALOG_COLUMN_2, CATALOG_COLUMN_3, CATALOG_COLUMN_4, CATALOG_COLUMN_5, CATALOG_TABLE_0, CATALOG_TABLE_1, CATALOG_TABLE_2, CATALOG_TABLE_3, CATALOG_TABLE_4, CATALOG_TABLE_5, CUTOFF_DATE, extralibs                                                                                                                                                                                                                                                                                                                   2
CATALOG_CODE_0, CATALOG_CODE_1, CATALOG_CODE_2, CATALOG_CODE_3, CATALOG_COLUMN_0, CATALOG_COLUMN_1, CATALOG_COLUMN_2, CATALOG_COLUMN_3, CATALOG_TABLE_0, CATALOG_TABLE_1, CATALOG_TABLE_2, CATALOG_TABLE_3, CUTOFF_DATE                                                                                                                                                                                                                                                                                                                                                                                                                                    2
CUTOFF_DATE, PREVIOUS_CUTOFF_DATE, extralibs                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               2
CATALOG_CODE_0, CATALOG_CODE_1, CATALOG_CODE_10, CATALOG_CODE_11, CATALOG_CODE_2, CATALOG_CODE_3, CATALOG_CODE_4, CATALOG_CODE_5, CATALOG_CODE_6, CATALOG_CODE_7, CATALOG_CODE_8, CATALOG_CODE_9, CATALOG_COLUMN_0, CATALOG_COLUMN_1, CATALOG_COLUMN_10, CATALOG_COLUMN_11, CATALOG_COLUMN_2, CATALOG_COLUMN_3, CATALOG_COLUMN_4, CATALOG_COLUMN_5, CATALOG_COLUMN_6, CATALOG_COLUMN_7, CATALOG_COLUMN_8, CATALOG_COLUMN_9, CATALOG_TABLE_0, CATALOG_TABLE_1, CATALOG_TABLE_10, CATALOG_TABLE_11, CATALOG_TABLE_2, CATALOG_TABLE_3, CATALOG_TABLE_4, CATALOG_TABLE_5, CATALOG_TABLE_6, CATALOG_TABLE_7, CATALOG_TABLE_8, CATALOG_TABLE_9, CUTOFF_DATE      2
ADOBE_REPORT_SUITE_NAME, CLOSING_DATE, DATE_VOLUMETRIC, LOWER_BOUND, UPPER_BOUND                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           2
CUTOFF_DATE, SOURCE, extralibs                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             2
CUTOFF_DATE, ENTIFIC_ID                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    2
CATALOG_CODE_0, CATALOG_CODE_1, CATALOG_CODE_2, CATALOG_CODE_3, CATALOG_CODE_4, CATALOG_CODE_5, CATALOG_CODE_6, CATALOG_CODE_7, CATALOG_COLUMN_0, CATALOG_COLUMN_1, CATALOG_COLUMN_2, CATALOG_COLUMN_3, CATALOG_COLUMN_4, CATALOG_COLUMN_5, CATALOG_COLUMN_6, CATALOG_COLUMN_7, CATALOG_TABLE_0, CATALOG_TABLE_1, CATALOG_TABLE_2, CATALOG_TABLE_3, CATALOG_TABLE_4, CATALOG_TABLE_5, CATALOG_TABLE_6, CATALOG_TABLE_7, CUTOFF_DATE, extralibs                                                                                                                                                                                                             1
CATALOG_CODE_0, CATALOG_CODE_1, CATALOG_COLUMN_0, CATALOG_COLUMN_1, CATALOG_TABLE_0, CATALOG_TABLE_1, CUTOFF_DATE, SOURCE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  1
CUTOFF_DATE, OPERATION_DATE, PREVIOUS_CUTOFF_DATE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          1
ADOBE_REPORT_SUITE_NAME, CLOSING_DATE, FECHA_VOLUMETRIC, LOWER_BOUND, UPPER_BOUND                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          1
CLOSING_DATE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               1
CATALOG_CODE_0, CATALOG_CODE_1, CATALOG_CODE_2, CATALOG_COLUMN_0, CATALOG_COLUMN_1, CATALOG_COLUMN_2, CATALOG_TABLE_0, CATALOG_TABLE_1, CATALOG_TABLE_2, CUTOFF_DATE, SOURCE                                                                                                                                                                                                                                                                                                                                                                                                                                                                               1
CATALOG_CODE_3, CATALOG_COLUMN_3, CATALOG_TABLE_3, CUTOFF_DATE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             1
ADOBE_REPORT_SUITE_NAME, CUTOFF_DATE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       1
CATALOG_CODE_1, CATALOG_CODE_2, CATALOG_CODE_3, CATALOG_CODE_4, CATALOG_COLUMN_1, CATALOG_COLUMN_2, CATALOG_COLUMN_3, CATALOG_COLUMN_4, CATALOG_TABLE_1, CATALOG_TABLE_2, CATALOG_TABLE_3, CATALOG_TABLE_4, CUTOFF_DATE                                                                                                                                                                                                                                                                                                                                                                                                                                    1